const actividadEconomicaFormsWeb = [
  {
    label: "ACTIVIDAD NO ECONOMICA",
    value: {
      Description: "NON-ECONOMIC ACTIVITY",
      CodigoSiaerp: "853",
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ACTIVIDAD NO ECONOMICA",
      value: "ANC",
    },
  },
  {
    label: "ACTIVIDADES INMOBILIARIAS",
    value: {
      Description: "REAL ESTATE ACTIVITIES",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ACTIVIDADES INMOBILIARIAS",
      value: "041",
    },
  },
  {
    label: "ACTIVIDADES PROFESIONALES, TECNICAS Y ADMINISTRATIVAS",
    value: {
      Description: "PROFESSIONAL, TECHNICAL, AND ADMINISTRATIVE ACTIVITIES",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ACTIVIDADES PROFESIONALES, TECNICAS Y ADMINISTRATIVAS",
      value: "042",
    },
  },
  {
    label: "ADMINISTRACION PUBLICA, DEFENSA; PLANES SEG SOCIAL OBLIGATORIA",
    value: {
      Description:
        "PUBLIC ADMINISTRATION, DEFENSE; MANDATORY SOCIAL SECURITY PLANS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ADMINISTRACION PUBLICA, DEFENSA; PLANES SEG SOCIAL OBLIGATORIA",
      value: "043",
    },
  },
  {
    label: "ALOJAMIENTO Y SERVICIOS DE COMIDA",
    value: {
      Description: "LODGING AND FOOD SERVICES",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ALOJAMIENTO Y SERVICIOS DE COMIDA",
      value: "036",
    },
  },
  {
    label:
      "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACION DE LOS VEHICULOS DE MOTOR Y DE LAS MOTOCICLETAS",
    value: {
      Description:
        "WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VEHICLES AND MOTORCYCLES",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label:
        "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACION DE LOS VEHICULOS DE MOTOR Y DE LAS MOTOCICLETAS",
      value: "035",
    },
  },
  {
    label: "CONSTRUCCION",
    value: {
      Description: "CONSTRUCTION",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "CONSTRUCCION",
      value: "034",
    },
  },
  {
    label: "CORREO, COMUNICACIONES E INFORMACION",
    value: {
      Description: "POSTAL, COMMUNICATIONS, AND INFORMATION",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "CORREO, COMUNICACIONES E INFORMACION",
      value: "038",
    },
  },
  {
    label: "CRIA DE ANIMALES",
    value: {
      Description: "ANIMAL HUSBANDRY",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "CRIA DE ANIMALES",
      value: "005",
    },
  },
  {
    label: "CRIA DE CAMARON",
    value: {
      Description: "SHRIMP FARMING",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "CRIA DE CAMARON",
      value: "007",
    },
  },
  {
    label: "CULTIVO DE BANANO, CAFE Y CACAO",
    value: {
      Description: "BANANA, COFFEE, AND COCOA CULTIVATION",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "CULTIVO DE BANANO, CAFE Y CACAO",
      value: "001",
    },
  },
  {
    label: "CULTIVO DE CEREALES",
    value: {
      Description: "CEREAL CULTIVATION",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "CULTIVO DE CEREALES",
      value: "002",
    },
  },
  {
    label: "CULTIVO DE FLORES",
    value: {
      Description: "FLOWER CULTIVATION",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "CULTIVO DE FLORES",
      value: "003",
    },
  },
  {
    label: "DEPENDIENTE",
    value: {
      Description: "DEPENDENT",
      CodigoSiaerp: "854",
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "DEPENDIENTE",
      value: "DEP",
    },
  },
  {
    label: "ELABORACION DE ACEITES Y GRASAS ORIGEN VEGETAL Y ANIMAL",
    value: {
      Description: "MANUFACTURE OF VEGETABLE AND ANIMAL OILS AND FATS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ELABORACION DE ACEITES Y GRASAS ORIGEN VEGETAL Y ANIMAL",
      value: "014",
    },
  },
  {
    label: "ELABORACION DE AZUCAR",
    value: {
      Description: "SUGAR MANUFACTURE",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ELABORACION DE AZUCAR",
      value: "017",
    },
  },
  {
    label: "ELABORACION DE BEBIDAS Y PRODUCTOS DE TABACO",
    value: {
      Description: "MANUFACTURE OF BEVERAGES AND TOBACCO PRODUCTS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ELABORACION DE BEBIDAS Y PRODUCTOS DE TABACO",
      value: "020",
    },
  },
  {
    label: "ELABORACION DE CACAO, CHOCOLATE Y PRODUCTOS CONFITERIA",
    value: {
      Description: "COCOA, CHOCOLATE, AND CONFECTIONERY PRODUCT MANUFACTURE",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ELABORACION DE CACAO, CHOCOLATE Y PRODUCTOS CONFITERIA",
      value: "018",
    },
  },
  {
    label: "ELABORACION DE OTROS PRODUCTOS ALIMENTICIOS",
    value: {
      Description: "MANUFACTURE OF OTHER FOOD PRODUCTS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ELABORACION DE OTROS PRODUCTOS ALIMENTICIOS",
      value: "019",
    },
  },
  {
    label: "ELABORACION DE PRODUCTOS DE MOLINERIA Y PANADERIA",
    value: {
      Description: "MILLING AND BAKERY PRODUCT MANUFACTURE",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ELABORACION DE PRODUCTOS DE MOLINERIA Y PANADERIA",
      value: "016",
    },
  },
  {
    label: "ELABORACION DE PRODUCTOS LACTEOS",
    value: {
      Description: "DAIRY PRODUCT MANUFACTURE",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ELABORACION DE PRODUCTOS LACTEOS",
      value: "015",
    },
  },
  {
    label: "ELABORACION Y CONSERVACION DE CAMARON",
    value: {
      Description: "SHRIMP PROCESSING AND PRESERVATION",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ELABORACION Y CONSERVACION DE CAMARON",
      value: "012",
    },
  },
  {
    label: "ELABORACION Y CONSERVACION DE PESCADO Y PRODUCTOS DE PESCADO",
    value: {
      Description: "FISH AND FISH PRODUCT PRESERVATION AND PROCESSING",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ELABORACION Y CONSERVACION DE PESCADO Y PRODUCTOS DE PESCADO",
      value: "013",
    },
  },
  {
    label: "ENSEÑANZA",
    value: {
      Description: "EDUCATION",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ENSEÑANZA",
      value: "044",
    },
  },
  {
    label: "ENTRETENIMIENTO, RECREACION Y OTRAS ACTIVIDADES DE SERVICIOS",
    value: {
      Description: "ENTERTAINMENT, RECREATION, AND OTHER SERVICE ACTIVITIES",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "ENTRETENIMIENTO, RECREACION Y OTRAS ACTIVIDADES DE SERVICIOS",
      value: "046",
    },
  },
  {
    label: "EXPLOTACION DE MINAS Y CANTERAS",
    value: {
      Description: "MINING AND QUARRYING",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "EXPLOTACION DE MINAS Y CANTERAS",
      value: "010",
    },
  },
  {
    label:
      "EXTRACCION PETROLEO, GAS NATURAL ACTIVIDADES DE SERVICIOS RELACIONADOS",
    value: {
      Description: "OIL AND NATURAL GAS EXTRACTION, RELATED SERVICE ACTIVITIES",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label:
        "EXTRACCION PETROLEO, GAS NATURAL ACTIVIDADES DE SERVICIOS RELACIONADOS",
      value: "009",
    },
  },
  {
    label: "FABRICACION DE EQUIPO DE TRANSPORTE",
    value: {
      Description: "MANUFACTURE OF TRANSPORT EQUIPMENT",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "FABRICACION DE EQUIPO DE TRANSPORTE",
      value: "030",
    },
  },
  {
    label: "FABRICACION DE INDUSTRIAS MANUFACTURERAS NCP",
    value: {
      Description: "MANUFACTURE OF OTHER MANUFACTURING INDUSTRIES NCP",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "FABRICACION DE INDUSTRIAS MANUFACTURERAS NCP",
      value: "032",
    },
  },
  {
    label: "FABRICACION DE MAQUINARIA Y EQUIPO",
    value: {
      Description: "MANUFACTURE OF MACHINERY AND EQUIPMENT",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "FABRICACION DE MAQUINARIA Y EQUIPO",
      value: "029",
    },
  },
  {
    label: "FABRICACION DE MUEBLES",
    value: {
      Description: "MANUFACTURE OF FURNITURE",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "FABRICACION DE MUEBLES",
      value: "031",
    },
  },
  {
    label: "FABRICACION DE OTROS PRODUCTOS MINERALES NO METALICOS",
    value: {
      Description: "MANUFACTURE OF OTHER NON-METALLIC MINERAL PRODUCTS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "FABRICACION DE OTROS PRODUCTOS MINERALES NO METALICOS",
      value: "027",
    },
  },
  {
    label: "FABRICACION DE PAPEL Y PRODUCTOS DE PAPEL",
    value: {
      Description: "MANUFACTURE OF PAPER AND PAPER PRODUCTS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "FABRICACION DE PAPEL Y PRODUCTOS DE PAPEL",
      value: "023",
    },
  },
  {
    label:
      "FABRICACION DE PRODUCTOS DE LA REFINACION PETROLEO Y DE OTROS PRODUCTOS",
    value: {
      Description:
        "MANUFACTURE OF REFINED PETROLEUM PRODUCTS AND OTHER RELATED PRODUCTS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label:
        "FABRICACION DE PRODUCTOS DE LA REFINACION PETROLEO Y DE OTROS PRODUCTOS",
      value: "024",
    },
  },
  {
    label: "FABRICACION DE PRODUCTOS DEL CAUCHO Y PLASTICO",
    value: {
      Description: "MANUFACTURE OF RUBBER AND PLASTIC PRODUCTS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "FABRICACION DE PRODUCTOS DEL CAUCHO Y PLASTICO",
      value: "026",
    },
  },
  {
    label:
      "FABRICACION DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR; FABRICACION DE CUERO Y ARTICULOS DE CUERO",
    value: {
      Description:
        "MANUFACTURE OF TEXTILE PRODUCTS, CLOTHING; LEATHER AND LEATHER PRODUCTS MANUFACTURE",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label:
        "FABRICACION DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR; FABRICACION DE CUERO Y ARTICULOS DE CUERO",
      value: "021",
    },
  },
  {
    label: "FABRICACION DE SUSTANCIAS Y PRODUCTOS QUIMICOS",
    value: {
      Description: "MANUFACTURE OF CHEMICALS AND CHEMICAL PRODUCTS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "FABRICACION DE SUSTANCIAS Y PRODUCTOS QUIMICOS",
      value: "025",
    },
  },
  {
    label: "FABRICACION METALES COMUNES Y DE PRODUCTOS ELABORADOS DE METAL",
    value: {
      Description: "MANUFACTURE OF COMMON METALS AND METAL PRODUCTS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "FABRICACION METALES COMUNES Y DE PRODUCTOS ELABORADOS DE METAL",
      value: "028",
    },
  },
  {
    label: "FINANCIACION DE PLANES DE SEGURO, EXCEPTO SEGURO SOCIAL",
    value: {
      Description: "INSURANCE PLAN FINANCING, EXCEPT SOCIAL INSURANCE",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "FINANCIACION DE PLANES DE SEGURO, EXCEPTO SEGURO SOCIAL",
      value: "040",
    },
  },
  {
    label: "HOGARES PRIVADOS CON SERVICIO DOMESTICO",
    value: {
      Description: "PRIVATE HOUSEHOLDS WITH DOMESTIC SERVICE",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "HOGARES PRIVADOS CON SERVICIO DOMESTICO",
      value: "047",
    },
  },
  {
    label: "INDEPENDIENTE",
    value: {
      Description: "INDEPENDENT",
      CodigoSiaerp: "855",
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "INDEPENDIENTE",
      value: "IND",
    },
  },
  {
    label: "INTERMEDIACION FINANCIERA",
    value: {
      Description: "FINANCIAL INTERMEDIATION",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "INTERMEDIACION FINANCIERA",
      value: "039",
    },
  },
  {
    label: "OTROS CULTIVOS",
    value: {
      Description: "OTHER CROPS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "OTROS CULTIVOS",
      value: "004",
    },
  },
  {
    label: "PESCA",
    value: {
      Description: "FISHING",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "PESCA",
      value: "008",
    },
  },
  {
    label: "PRODUCCION DE MADERA Y DE PRODUCTOS DE MADERA",
    value: {
      Description: "PRODUCTION OF WOOD AND WOOD PRODUCTS",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "PRODUCCION DE MADERA Y DE PRODUCTOS DE MADERA",
      value: "022",
    },
  },
  {
    label: "PRODUCCION, PROCESAMIENTO Y CONSERVA DE CARNE Y PRODUCTOS CARNICOS",
    value: {
      Description:
        "MEAT AND MEAT PRODUCT PRODUCTION, PROCESSING, AND PRESERVATION",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label:
        "PRODUCCION, PROCESAMIENTO Y CONSERVA DE CARNE Y PRODUCTOS CARNICOS",
      value: "011",
    },
  },
  {
    label: "SERVICIOS SOCIALES Y DE SALUD",
    value: {
      Description: "SOCIAL AND HEALTH SERVICES",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "SERVICIOS SOCIALES Y DE SALUD",
      value: "045",
    },
  },
  {
    label:
      "SILVICULTURA, EXTRACCION, MADERA Y ACTIVIDADES DE SERVICIOS CONEXAS",
    value: {
      Description: "FORESTRY, LOGGING, AND RELATED SERVICE ACTIVITIES",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label:
        "SILVICULTURA, EXTRACCION, MADERA Y ACTIVIDADES DE SERVICIOS CONEXAS",
      value: "006",
    },
  },
  {
    label: "SUMINISTRO DE ELECTRICIDAD Y AGUA",
    value: {
      Description: "SUPPLY OF ELECTRICITY AND WATER",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "SUMINISTRO DE ELECTRICIDAD Y AGUA",
      value: "033",
    },
  },
  {
    label: "TRANSPORTE Y ALMACENAMIENTO",
    value: {
      Description: "TRANSPORTATION AND STORAGE",
      CodigoSiaerp: null,
      CodigoZoho: null,
      CodigoVT: null,
      CodigoPadre: "0",
      Abreviado: null,
      Nivel: 1,
      NivelFinal: "N",
      label: "TRANSPORTE Y ALMACENAMIENTO",
      value: "037",
    },
  },
];

export { actividadEconomicaFormsWeb };
