const listNacionalidadFormsWeb = [
  {
    label: "AFGANISTAN",
    value: {
      CodigoSierp: "17",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AFGHANISTAN",
      label: "AFGANISTAN",
      value: "AFG",
    },
  },
  {
    label: "ALBANIA",
    value: {
      CodigoSierp: "7",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ALBANIA",
      label: "ALBANIA",
      value: "ALB",
    },
  },
  {
    label: "ALEMANIA",
    value: {
      CodigoSierp: "8",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GERMANY",
      label: "ALEMANIA",
      value: "DEU",
    },
  },
  {
    label: "ANDORRA",
    value: {
      CodigoSierp: "9",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ANDORRA",
      label: "ANDORRA",
      value: "AND",
    },
  },
  {
    label: "ANGOLA",
    value: {
      CodigoSierp: "10",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ANGOLA",
      label: "ANGOLA",
      value: "AGO",
    },
  },
  {
    label: "ANGUILA",
    value: {
      CodigoSierp: "19",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ANGUILLA",
      label: "ANGUILA",
      value: "AIA",
    },
  },
  {
    label: "ANTARTIDA",
    value: {
      CodigoSierp: "20",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ANTARCTICA",
      label: "ANTARTIDA",
      value: "ATA",
    },
  },
  {
    label: "ANTIGUA Y BARBUDA",
    value: {
      CodigoSierp: "11",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ANTIGUA AND BARBUDA",
      label: "ANTIGUA Y BARBUDA",
      value: "ATG",
    },
  },
  {
    label: "ANTILLAS NEERLANDESAS",
    value: {
      CodigoSierp: "21",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NETHERLANDS ANTILLES",
      label: "ANTILLAS NEERLANDESAS",
      value: "ANT",
    },
  },
  {
    label: "ARABIA SAUDITA",
    value: {
      CodigoSierp: "22",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SAUDI ARABIA",
      label: "ARABIA SAUDITA",
      value: "SAU",
    },
  },
  {
    label: "ARGELIA",
    value: {
      CodigoSierp: "24",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ALGERIA",
      label: "ARGELIA",
      value: "DZA",
    },
  },
  {
    label: "ARGENTINA",
    value: {
      CodigoSierp: "25",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ARGENTINA",
      label: "ARGENTINA",
      value: "ARG",
    },
  },
  {
    label: "ARMENIA",
    value: {
      CodigoSierp: "26",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ARMENIA",
      label: "ARMENIA",
      value: "ARM",
    },
  },
  {
    label: "ARUBA",
    value: {
      CodigoSierp: "27",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ARUBA",
      label: "ARUBA",
      value: "ABW",
    },
  },
  {
    label: "AUSTRALIA",
    value: {
      CodigoSierp: "16",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AUSTRALIA",
      label: "AUSTRALIA",
      value: "AUS",
    },
  },
  {
    label: "AUSTRIA",
    value: {
      CodigoSierp: "30",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AUSTRIA",
      label: "AUSTRIA",
      value: "AUT",
    },
  },
  {
    label: "AZERBAIYAN",
    value: {
      CodigoSierp: "31",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AZERBAIJAN",
      label: "AZERBAIYAN",
      value: "AZE",
    },
  },
  {
    label: "BAHAMAS",
    value: {
      CodigoSierp: "32",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BAHAMAS",
      label: "BAHAMAS",
      value: "BHS",
    },
  },
  {
    label: "BAHREIN",
    value: {
      CodigoSierp: "33",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BAHRAIN",
      label: "BAHREIN",
      value: "BHR",
    },
  },
  {
    label: "BANGLADESH",
    value: {
      CodigoSierp: "34",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BANGLADESH",
      label: "BANGLADESH",
      value: "BGD",
    },
  },
  {
    label: "BARBADOS",
    value: {
      CodigoSierp: "35",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BARBADOS",
      label: "BARBADOS",
      value: "BRB",
    },
  },
  {
    label: "BELGICA",
    value: {
      CodigoSierp: "385",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BELGIUM",
      label: "BELGICA",
      value: "BEL",
    },
  },
  {
    label: "BELICE",
    value: {
      CodigoSierp: "37",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BELIZE",
      label: "BELICE",
      value: "BLZ",
    },
  },
  {
    label: "BENIN",
    value: {
      CodigoSierp: "38",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BENIN",
      label: "BENIN",
      value: "BEN",
    },
  },
  {
    label: "BERMUDAS",
    value: {
      CodigoSierp: "39",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BERMUDA",
      label: "BERMUDAS",
      value: "BMU",
    },
  },
  {
    label: "BIELORRUSIA",
    value: {
      CodigoSierp: "40",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BELARUS",
      label: "BIELORRUSIA",
      value: "BLR",
    },
  },
  {
    label: "BIRMANIA",
    value: {
      CodigoSierp: "41",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BURMA",
      label: "BIRMANIA",
      value: "MMR",
    },
  },
  {
    label: "BOLIVIA",
    value: {
      CodigoSierp: "42",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BOLIVIA",
      label: "BOLIVIA",
      value: "BOL",
    },
  },
  {
    label: "BOSNIA Y HERZEGOVINA",
    value: {
      CodigoSierp: "43",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BOSNIA AND HERZEGOVINA",
      label: "BOSNIA Y HERZEGOVINA",
      value: "BIH",
    },
  },
  {
    label: "BOTSUANA",
    value: {
      CodigoSierp: "44",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BOTSWANA",
      label: "BOTSUANA",
      value: "BWA",
    },
  },
  {
    label: "BRASIL",
    value: {
      CodigoSierp: "45",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BRAZIL",
      label: "BRASIL",
      value: "BRA",
    },
  },
  {
    label: "BRUNEI",
    value: {
      CodigoSierp: "46",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BRUNEI",
      label: "BRUNEI",
      value: "BRN",
    },
  },
  {
    label: "BULGARIA",
    value: {
      CodigoSierp: "47",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BULGARIA",
      label: "BULGARIA",
      value: "BGR",
    },
  },
  {
    label: "BURKINA FASO",
    value: {
      CodigoSierp: "48",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BURKINA FASO",
      label: "BURKINA FASO",
      value: "BFA",
    },
  },
  {
    label: "BURUNDI",
    value: {
      CodigoSierp: "49",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BURUNDI",
      label: "BURUNDI",
      value: "BDI",
    },
  },
  {
    label: "BUTAN",
    value: {
      CodigoSierp: "50",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BHUTAN",
      label: "BUTAN",
      value: "BTN",
    },
  },
  {
    label: "CABO VERDE",
    value: {
      CodigoSierp: "51",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CAPE VERDE",
      label: "CABO VERDE",
      value: "CPV",
    },
  },
  {
    label: "CAMBOYA",
    value: {
      CodigoSierp: "52",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CAMBODIA",
      label: "CAMBOYA",
      value: "KHM",
    },
  },
  {
    label: "CAMERUN",
    value: {
      CodigoSierp: "53",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CAMEROON",
      label: "CAMERUN",
      value: "CMR",
    },
  },
  {
    label: "CANADA",
    value: {
      CodigoSierp: "379",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CANADA",
      label: "CANADA",
      value: "CAN",
    },
  },
  {
    label: "CHAD",
    value: {
      CodigoSierp: "55",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CHAD",
      label: "CHAD",
      value: "TCD",
    },
  },
  {
    label: "CHILE",
    value: {
      CodigoSierp: "56",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CHILE",
      label: "CHILE",
      value: "CHL",
    },
  },
  {
    label: "CHINA",
    value: {
      CodigoSierp: "382",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CHINA",
      label: "CHINA",
      value: "CHN",
    },
  },
  {
    label: "CHIPRE",
    value: {
      CodigoSierp: "57",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CYPRUS",
      label: "CHIPRE",
      value: "CYP",
    },
  },
  {
    label: "CIUDAD DEL VATICANO",
    value: {
      CodigoSierp: "72",
      CodigoSos: null,
      CodigoVt: null,
      Value: "VATICAN CITY",
      label: "CIUDAD DEL VATICANO",
      value: "VAT",
    },
  },
  {
    label: "COLOMBIA",
    value: {
      CodigoSierp: "5",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COLOMBIA",
      label: "COLOMBIA",
      value: "COL",
    },
  },
  {
    label: "COMORAS",
    value: {
      CodigoSierp: "59",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COMOROS",
      label: "COMORAS",
      value: "COM",
    },
  },
  {
    label: "COREA DEL NORTE",
    value: {
      CodigoSierp: "62",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NORTH KOREA",
      label: "COREA DEL NORTE",
      value: "PRK",
    },
  },
  {
    label: "COREA DEL SUR",
    value: {
      CodigoSierp: "63",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOUTH KOREA",
      label: "COREA DEL SUR",
      value: "KOR",
    },
  },
  {
    label: "COSTA DE MARFIL",
    value: {
      CodigoSierp: "64",
      CodigoSos: null,
      CodigoVt: null,
      Value: "IVORY COAST",
      label: "COSTA DE MARFIL",
      value: "CIV",
    },
  },
  {
    label: "COSTA RICA",
    value: {
      CodigoSierp: "65",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COSTA RICA",
      label: "COSTA RICA",
      value: "CRI",
    },
  },
  {
    label: "CROACIA",
    value: {
      CodigoSierp: "66",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CROATIA",
      label: "CROACIA",
      value: "HRV",
    },
  },
  {
    label: "CUBA",
    value: {
      CodigoSierp: "67",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CUBA",
      label: "CUBA",
      value: "CUB",
    },
  },
  {
    label: "DINAMARCA",
    value: {
      CodigoSierp: "69",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DENMARK",
      label: "DINAMARCA",
      value: "DNK",
    },
  },
  {
    label: "DOMINICA",
    value: {
      CodigoSierp: "70",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DOMINICA",
      label: "DOMINICA",
      value: "DMA",
    },
  },
  {
    label: "ECUADOR",
    value: {
      CodigoSierp: "1",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ECUADOR",
      label: "ECUADOR",
      value: "ECU",
    },
  },
  {
    label: "EGIPTO",
    value: {
      CodigoSierp: "3",
      CodigoSos: null,
      CodigoVt: null,
      Value: "EGYPT",
      label: "EGIPTO",
      value: "EGY",
    },
  },
  {
    label: "EL SALVADOR",
    value: {
      CodigoSierp: "71",
      CodigoSos: null,
      CodigoVt: null,
      Value: "EL SALVADOR",
      label: "EL SALVADOR",
      value: "SLV",
    },
  },
  {
    label: "EMIRATOS ARABES UNIDOS",
    value: {
      CodigoSierp: "73",
      CodigoSos: null,
      CodigoVt: null,
      Value: "UNITED ARAB EMIRATES",
      label: "EMIRATOS ARABES UNIDOS",
      value: "ARE",
    },
  },
  {
    label: "ERITREA",
    value: {
      CodigoSierp: "74",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ERITREA",
      label: "ERITREA",
      value: "ERI",
    },
  },
  {
    label: "ESLOVAQUIA",
    value: {
      CodigoSierp: "75",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SLOVAKIA",
      label: "ESLOVAQUIA",
      value: "SVK",
    },
  },
  {
    label: "ESLOVENIA",
    value: {
      CodigoSierp: "76",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SLOVENIA",
      label: "ESLOVENIA",
      value: "SVN",
    },
  },
  {
    label: "ESPAÑA",
    value: {
      CodigoSierp: "77",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SPAIN",
      label: "ESPAÑA",
      value: "ESP",
    },
  },
  {
    label: "ESTADOS FEDERADOS DE MICRONESIA",
    value: {
      CodigoSierp: "162",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FEDERATED STATES OF MICRONESIA",
      label: "ESTADOS FEDERADOS DE MICRONESIA",
      value: "FSM",
    },
  },
  {
    label: "ESTADOS UNIDOS",
    value: {
      CodigoSierp: "14",
      CodigoSos: null,
      CodigoVt: null,
      Value: "UNITED STATES",
      label: "ESTADOS UNIDOS",
      value: "USA",
    },
  },
  {
    label: "ESTONIA",
    value: {
      CodigoSierp: "78",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ESTONIA",
      label: "ESTONIA",
      value: "EST",
    },
  },
  {
    label: "ETIOPIA",
    value: {
      CodigoSierp: "79",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ETHIOPIA",
      label: "ETIOPIA",
      value: "ETH",
    },
  },
  {
    label: "FILIPINAS",
    value: {
      CodigoSierp: "80",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PHILIPPINES",
      label: "FILIPINAS",
      value: "PHL",
    },
  },
  {
    label: "FINLANDIA",
    value: {
      CodigoSierp: "81",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FINLAND",
      label: "FINLANDIA",
      value: "FIN",
    },
  },
  {
    label: "FIYI",
    value: {
      CodigoSierp: "82",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FIJI",
      label: "FIYI",
      value: "FJI",
    },
  },
  {
    label: "FRANCIA",
    value: {
      CodigoSierp: "83",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FRANCE",
      label: "FRANCIA",
      value: "FRA",
    },
  },
  {
    label: "GABON",
    value: {
      CodigoSierp: "84",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GABON",
      label: "GABON",
      value: "GAB",
    },
  },
  {
    label: "GAMBIA",
    value: {
      CodigoSierp: "85",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GAMBIA",
      label: "GAMBIA",
      value: "GMB",
    },
  },
  {
    label: "GEORGIA",
    value: {
      CodigoSierp: "87",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GEORGIA",
      label: "GEORGIA",
      value: "GEO",
    },
  },
  {
    label: "GHANA",
    value: {
      CodigoSierp: "88",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GHANA",
      label: "GHANA",
      value: "GHA",
    },
  },
  {
    label: "GIBRALTAR",
    value: {
      CodigoSierp: "89",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GIBRALTAR",
      label: "GIBRALTAR",
      value: "GIB",
    },
  },
  {
    label: "GRANADA",
    value: {
      CodigoSierp: "90",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRENADA",
      label: "GRANADA",
      value: "GRD",
    },
  },
  {
    label: "GRECIA",
    value: {
      CodigoSierp: "91",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GREECE",
      label: "GRECIA",
      value: "GRC",
    },
  },
  {
    label: "GROENLANDIA",
    value: {
      CodigoSierp: "92",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GREENLAND",
      label: "GROENLANDIA",
      value: "GRL",
    },
  },
  {
    label: "GUAM",
    value: {
      CodigoSierp: "93",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GUAM",
      label: "GUAM",
      value: "GUM",
    },
  },
  {
    label: "GUATEMALA",
    value: {
      CodigoSierp: "13",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GUATEMALA",
      label: "GUATEMALA",
      value: "GTM",
    },
  },
  {
    label: "GUERNSEY",
    value: {
      CodigoSierp: "94",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GUERNSEY",
      label: "GUERNSEY",
      value: "GGY",
    },
  },
  {
    label: "GUINEA",
    value: {
      CodigoSierp: "95",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GUINEA",
      label: "GUINEA",
      value: "GIN",
    },
  },
  {
    label: "GUINEA ECUATORIAL",
    value: {
      CodigoSierp: "96",
      CodigoSos: null,
      CodigoVt: null,
      Value: "EQUATORIAL GUINEA",
      label: "GUINEA ECUATORIAL",
      value: "GNQ",
    },
  },
  {
    label: "GUINEA-BISSAU",
    value: {
      CodigoSierp: "97",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GUINEA-BISSAU",
      label: "GUINEA-BISSAU",
      value: "GNB",
    },
  },
  {
    label: "GUYANA",
    value: {
      CodigoSierp: "98",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GUYANA",
      label: "GUYANA",
      value: "GUY",
    },
  },
  {
    label: "HAITI",
    value: {
      CodigoSierp: "99",
      CodigoSos: null,
      CodigoVt: null,
      Value: "HAITI",
      label: "HAITI",
      value: "HTI",
    },
  },
  {
    label: "HONDURAS",
    value: {
      CodigoSierp: "100",
      CodigoSos: null,
      CodigoVt: null,
      Value: "HONDURAS",
      label: "HONDURAS",
      value: "HND",
    },
  },
  {
    label: "HONG KONG",
    value: {
      CodigoSierp: "101",
      CodigoSos: null,
      CodigoVt: null,
      Value: "HONG KONG",
      label: "HONG KONG",
      value: "HKG",
    },
  },
  {
    label: "HUNGRIA",
    value: {
      CodigoSierp: "102",
      CodigoSos: null,
      CodigoVt: null,
      Value: "HUNGARY",
      label: "HUNGRIA",
      value: "HUN",
    },
  },
  {
    label: "INDIA",
    value: {
      CodigoSierp: "103",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INDIA",
      label: "INDIA",
      value: "IND",
    },
  },
  {
    label: "INDONESIA",
    value: {
      CodigoSierp: "105",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INDONESIA",
      label: "INDONESIA",
      value: "IDN",
    },
  },
  {
    label: "IRAK",
    value: {
      CodigoSierp: "107",
      CodigoSos: null,
      CodigoVt: null,
      Value: "IRAQ",
      label: "IRAK",
      value: "IRQ",
    },
  },
  {
    label: "IRAN",
    value: {
      CodigoSierp: "106",
      CodigoSos: null,
      CodigoVt: null,
      Value: "IRAN",
      label: "IRAN",
      value: "IRN",
    },
  },
  {
    label: "IRLANDA",
    value: {
      CodigoSierp: "108",
      CodigoSos: null,
      CodigoVt: null,
      Value: "IRELAND",
      label: "IRLANDA",
      value: "IRL",
    },
  },
  {
    label: "ISLA DE MAN",
    value: {
      CodigoSierp: "156",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ISLE OF MAN",
      label: "ISLA DE MAN",
      value: "IMN",
    },
  },
  {
    label: "ISLA DE NAVIDAD",
    value: {
      CodigoSierp: "110",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CHRISTMAS ISLAND",
      label: "ISLA DE NAVIDAD",
      value: "CXR",
    },
  },
  {
    label: "ISLA MONTSERRAT",
    value: {
      CodigoSierp: "167",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MONTSERRAT",
      label: "ISLA MONTSERRAT",
      value: "MSR",
    },
  },
  {
    label: "ISLA SANTA ELENA",
    value: {
      CodigoSierp: "210",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SAINT HELENA",
      label: "ISLA SANTA ELENA",
      value: "SHN",
    },
  },
  {
    label: "ISLANDIA",
    value: {
      CodigoSierp: "112",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ICELAND",
      label: "ISLANDIA",
      value: "ISL",
    },
  },
  {
    label: "ISLAS CAIMAN",
    value: {
      CodigoSierp: "113",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CAYMAN ISLANDS",
      label: "ISLAS CAIMAN",
      value: "CYM",
    },
  },
  {
    label: "ISLAS COCOS",
    value: {
      CodigoSierp: "114",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COCOS (KEELING) ISLANDS",
      label: "ISLAS COCOS",
      value: "CCK",
    },
  },
  {
    label: "ISLAS COOK",
    value: {
      CodigoSierp: "115",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COOK ISLANDS",
      label: "ISLAS COOK",
      value: "COK",
    },
  },
  {
    label: "ISLAS FEROE",
    value: {
      CodigoSierp: "116",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FAROE ISLANDS",
      label: "ISLAS FEROE",
      value: "FRO",
    },
  },
  {
    label: "ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR",
    value: {
      CodigoSierp: "117",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
      label: "ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR",
      value: "SGS",
    },
  },
  {
    label: "ISLAS HEARD Y MCDONALD",
    value: {
      CodigoSierp: "118",
      CodigoSos: null,
      CodigoVt: null,
      Value: "HEARD ISLAND AND MCDONALD ISLANDS",
      label: "ISLAS HEARD Y MCDONALD",
      value: "HMD",
    },
  },
  {
    label: "ISLAS MALVINAS",
    value: {
      CodigoSierp: "119",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FALKLAND ISLANDS",
      label: "ISLAS MALVINAS",
      value: "FLK",
    },
  },
  {
    label: "ISLAS MARIANAS DEL NORTE",
    value: {
      CodigoSierp: "120",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NORTHERN MARIANA ISLANDS",
      label: "ISLAS MARIANAS DEL NORTE",
      value: "MNP",
    },
  },
  {
    label: "ISLAS MARSHALL",
    value: {
      CodigoSierp: "121",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MARSHALL ISLANDS",
      label: "ISLAS MARSHALL",
      value: "MHL",
    },
  },
  {
    label: "ISLAS PITCAIRN",
    value: {
      CodigoSierp: "122",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PITCAIRN ISLANDS",
      label: "ISLAS PITCAIRN",
      value: "PCN",
    },
  },
  {
    label: "ISLAS SALOMON",
    value: {
      CodigoSierp: "123",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOLOMON ISLANDS",
      label: "ISLAS SALOMON",
      value: "SLB",
    },
  },
  {
    label: "ISLAS TURCAS Y CAICOS",
    value: {
      CodigoSierp: "124",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TURKS AND CAICOS ISLANDS",
      label: "ISLAS TURCAS Y CAICOS",
      value: "TCA",
    },
  },
  {
    label: "ISLAS ULTRAMARINAS DE ESTADOS UNIDOS",
    value: {
      CodigoSierp: "252",
      CodigoSos: null,
      CodigoVt: null,
      Value: "UNITED STATES MINOR OUTLYING ISLANDS",
      label: "ISLAS ULTRAMARINAS DE ESTADOS UNIDOS",
      value: "UMI",
    },
  },
  {
    label: "ISLAS VIRGENES BRITANICAS",
    value: {
      CodigoSierp: "126",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BRITISH VIRGIN ISLANDS",
      label: "ISLAS VIRGENES BRITANICAS",
      value: "VGB",
    },
  },
  {
    label: "ISLAS VIRGENES DE LOS ESTADOS UNIDOS",
    value: {
      CodigoSierp: "125",
      CodigoSos: null,
      CodigoVt: null,
      Value: "UNITED STATES VIRGIN ISLANDS",
      label: "ISLAS VIRGENES DE LOS ESTADOS UNIDOS",
      value: "VIR",
    },
  },
  {
    label: "ISRAEL",
    value: {
      CodigoSierp: "127",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ISRAEL",
      label: "ISRAEL",
      value: "ISR",
    },
  },
  {
    label: "ITALIA",
    value: {
      CodigoSierp: "128",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ITALY",
      label: "ITALIA",
      value: "ITA",
    },
  },
  {
    label: "JAMAICA",
    value: {
      CodigoSierp: "129",
      CodigoSos: null,
      CodigoVt: null,
      Value: "JAMAICA",
      label: "JAMAICA",
      value: "JAM",
    },
  },
  {
    label: "JAPON",
    value: {
      CodigoSierp: "264",
      CodigoSos: null,
      CodigoVt: null,
      Value: "JAPAN",
      label: "JAPON",
      value: "JPN",
    },
  },
  {
    label: "JERSEY",
    value: {
      CodigoSierp: "132",
      CodigoSos: null,
      CodigoVt: null,
      Value: "JERSEY",
      label: "JERSEY",
      value: "JEY",
    },
  },
  {
    label: "JORDANIA",
    value: {
      CodigoSierp: "133",
      CodigoSos: null,
      CodigoVt: null,
      Value: "JORDAN",
      label: "JORDANIA",
      value: "JOR",
    },
  },
  {
    label: "KAZAJISTAN",
    value: {
      CodigoSierp: "134",
      CodigoSos: null,
      CodigoVt: null,
      Value: "KAZAKHSTAN",
      label: "KAZAJISTAN",
      value: "KAZ",
    },
  },
  {
    label: "KENIA",
    value: {
      CodigoSierp: "135",
      CodigoSos: null,
      CodigoVt: null,
      Value: "KENYA",
      label: "KENIA",
      value: "KEN",
    },
  },
  {
    label: "KIRGUISTAN",
    value: {
      CodigoSierp: "136",
      CodigoSos: null,
      CodigoVt: null,
      Value: "KYRGYZSTAN",
      label: "KIRGUISTAN",
      value: "KGZ",
    },
  },
  {
    label: "KIRIBATI",
    value: {
      CodigoSierp: "137",
      CodigoSos: null,
      CodigoVt: null,
      Value: "KIRIBATI",
      label: "KIRIBATI",
      value: "KIR",
    },
  },
  {
    label: "KUWAIT",
    value: {
      CodigoSierp: "138",
      CodigoSos: null,
      CodigoVt: null,
      Value: "KUWAIT",
      label: "KUWAIT",
      value: "KWT",
    },
  },
  {
    label: "LAOS",
    value: {
      CodigoSierp: "139",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LAOS",
      label: "LAOS",
      value: "LAO",
    },
  },
  {
    label: "LESOTO",
    value: {
      CodigoSierp: "140",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LESOTHO",
      label: "LESOTO",
      value: "LSO",
    },
  },
  {
    label: "LETONIA",
    value: {
      CodigoSierp: "141",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LATVIA",
      label: "LETONIA",
      value: "LVA",
    },
  },
  {
    label: "LIBANO",
    value: {
      CodigoSierp: "142",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LEBANON",
      label: "LIBANO",
      value: "LBN",
    },
  },
  {
    label: "LIBERIA",
    value: {
      CodigoSierp: "143",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LIBERIA",
      label: "LIBERIA",
      value: "LBR",
    },
  },
  {
    label: "LIBIA",
    value: {
      CodigoSierp: "144",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LIBYA",
      label: "LIBIA",
      value: "LBY",
    },
  },
  {
    label: "LIECHTENSTEIN",
    value: {
      CodigoSierp: "145",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LIECHTENSTEIN",
      label: "LIECHTENSTEIN",
      value: "LIE",
    },
  },
  {
    label: "LITUANIA",
    value: {
      CodigoSierp: "146",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LITHUANIA",
      label: "LITUANIA",
      value: "LTU",
    },
  },
  {
    label: "LUXEMBURGO",
    value: {
      CodigoSierp: "147",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LUXEMBOURG",
      label: "LUXEMBURGO",
      value: "LUX",
    },
  },
  {
    label: "MACAO",
    value: {
      CodigoSierp: "148",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MACAO",
      label: "MACAO",
      value: "MAC",
    },
  },
  {
    label: "MACEDONIA DEL NORTE",
    value: {
      CodigoSierp: "149",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NORTH MACEDONIA",
      label: "MACEDONIA DEL NORTE",
      value: "MKD",
    },
  },
  {
    label: "MADAGASCAR",
    value: {
      CodigoSierp: "150",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MADAGASCAR",
      label: "MADAGASCAR",
      value: "MDG",
    },
  },
  {
    label: "MALASIA",
    value: {
      CodigoSierp: "151",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MALAYSIA",
      label: "MALASIA",
      value: "MYS",
    },
  },
  {
    label: "MALAUI",
    value: {
      CodigoSierp: "152",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MALAWI",
      label: "MALAUI",
      value: "MWI",
    },
  },
  {
    label: "MALDIVAS",
    value: {
      CodigoSierp: "153",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MALDIVES",
      label: "MALDIVAS",
      value: "MDV",
    },
  },
  {
    label: "MALI",
    value: {
      CodigoSierp: "154",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MALI",
      label: "MALI",
      value: "MLI",
    },
  },
  {
    label: "MALTA",
    value: {
      CodigoSierp: "155",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MALTA",
      label: "MALTA",
      value: "MLT",
    },
  },
  {
    label: "MARRUECOS",
    value: {
      CodigoSierp: "157",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MOROCCO",
      label: "MARRUECOS",
      value: "MAR",
    },
  },
  {
    label: "MAURICIO",
    value: {
      CodigoSierp: "158",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MAURITIUS",
      label: "MAURICIO",
      value: "MUS",
    },
  },
  {
    label: "MAURITANIA",
    value: {
      CodigoSierp: "159",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MAURITANIA",
      label: "MAURITANIA",
      value: "MRT",
    },
  },
  {
    label: "MAYOTTE",
    value: {
      CodigoSierp: "160",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MAYOTTE",
      label: "MAYOTTE",
      value: "MYT",
    },
  },
  {
    label: "MEXICO",
    value: {
      CodigoSierp: "259",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MEXICO",
      label: "MEXICO",
      value: "MEX",
    },
  },
  {
    label: "MOLDAVIA",
    value: {
      CodigoSierp: "163",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MOLDOVA",
      label: "MOLDAVIA",
      value: "MDA",
    },
  },
  {
    label: "MONACO",
    value: {
      CodigoSierp: "164",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MONACO",
      label: "MONACO",
      value: "MCO",
    },
  },
  {
    label: "MONGOLIA",
    value: {
      CodigoSierp: "165",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MONGOLIA",
      label: "MONGOLIA",
      value: "MNG",
    },
  },
  {
    label: "MONTENEGRO",
    value: {
      CodigoSierp: "166",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MONTENEGRO",
      label: "MONTENEGRO",
      value: "MNE",
    },
  },
  {
    label: "MOZAMBIQUE",
    value: {
      CodigoSierp: "168",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MOZAMBIQUE",
      label: "MOZAMBIQUE",
      value: "MOZ",
    },
  },
  {
    label: "NAMIBIA",
    value: {
      CodigoSierp: "170",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NAMIBIA",
      label: "NAMIBIA",
      value: "NAM",
    },
  },
  {
    label: "NAURU",
    value: {
      CodigoSierp: "171",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NAURU",
      label: "NAURU",
      value: "NRU",
    },
  },
  {
    label: "NEPAL",
    value: {
      CodigoSierp: "173",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NEPAL",
      label: "NEPAL",
      value: "NPL",
    },
  },
  {
    label: "NICARAGUA",
    value: {
      CodigoSierp: "174",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NICARAGUA",
      label: "NICARAGUA",
      value: "NIC",
    },
  },
  {
    label: "NIGER",
    value: {
      CodigoSierp: "175",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NIGER",
      label: "NIGER",
      value: "NER",
    },
  },
  {
    label: "NIGERIA",
    value: {
      CodigoSierp: "176",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NIGERIA",
      label: "NIGERIA",
      value: "NGA",
    },
  },
  {
    label: "NIUE",
    value: {
      CodigoSierp: "177",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NIUE",
      label: "NIUE",
      value: "NIU",
    },
  },
  {
    label: "NORFOLK",
    value: {
      CodigoSierp: "111",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NORFOLK ISLAND",
      label: "NORFOLK",
      value: "NFK",
    },
  },
  {
    label: "NORUEGA",
    value: {
      CodigoSierp: "178",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NORWAY",
      label: "NORUEGA",
      value: "NOR",
    },
  },
  {
    label: "NUEVA CALEDONIA",
    value: {
      CodigoSierp: "179",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NEW CALEDONIA",
      label: "NUEVA CALEDONIA",
      value: "NCL",
    },
  },
  {
    label: "NUEVA ZELANDA",
    value: {
      CodigoSierp: "180",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NEW ZEALAND",
      label: "NUEVA ZELANDA",
      value: "NZL",
    },
  },
  {
    label: "OMAN",
    value: {
      CodigoSierp: "181",
      CodigoSos: null,
      CodigoVt: null,
      Value: "OMAN",
      label: "OMAN",
      value: "OMN",
    },
  },
  {
    label: "PAISES BAJOS (HOLANDA)",
    value: {
      CodigoSierp: "183",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NETHERLANDS",
      label: "PAISES BAJOS (HOLANDA)",
      value: "NLD",
    },
  },
  {
    label: "PAKISTAN",
    value: {
      CodigoSierp: "184",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PAKISTAN",
      label: "PAKISTAN",
      value: "PAK",
    },
  },
  {
    label: "PALAOS",
    value: {
      CodigoSierp: "185",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PALAU",
      label: "PALAOS",
      value: "PLW",
    },
  },
  {
    label: "PANAMA",
    value: {
      CodigoSierp: "12",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PANAMA",
      label: "PANAMA",
      value: "PAN",
    },
  },
  {
    label: "PAPUA NUEVA GUINEA",
    value: {
      CodigoSierp: "186",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PAPUA NEW GUINEA",
      label: "PAPUA NUEVA GUINEA",
      value: "PNG",
    },
  },
  {
    label: "PARAGUAY",
    value: {
      CodigoSierp: "188",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PARAGUAY",
      label: "PARAGUAY",
      value: "PRY",
    },
  },
  {
    label: "PERU",
    value: {
      CodigoSierp: "189",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PERU",
      label: "PERU",
      value: "PER",
    },
  },
  {
    label: "POLINESIA FRANCESA",
    value: {
      CodigoSierp: "190",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FRENCH POLYNESIA",
      label: "POLINESIA FRANCESA",
      value: "PYF",
    },
  },
  {
    label: "POLONIA",
    value: {
      CodigoSierp: "191",
      CodigoSos: null,
      CodigoVt: null,
      Value: "POLAND",
      label: "POLONIA",
      value: "POL",
    },
  },
  {
    label: "PORTUGAL",
    value: {
      CodigoSierp: "192",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PORTUGAL",
      label: "PORTUGAL",
      value: "PRT",
    },
  },
  {
    label: "PUERTO RICO",
    value: {
      CodigoSierp: "193",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PUERTO RICO",
      label: "PUERTO RICO",
      value: "PRI",
    },
  },
  {
    label: "QATAR",
    value: {
      CodigoSierp: "194",
      CodigoSos: null,
      CodigoVt: null,
      Value: "QATAR",
      label: "QATAR",
      value: "QAT",
    },
  },
  {
    label: "REINO UNIDO",
    value: {
      CodigoSierp: "195",
      CodigoSos: null,
      CodigoVt: null,
      Value: "UNITED KINGDOM",
      label: "REINO UNIDO",
      value: "GBR",
    },
  },
  {
    label: "REPUBLICA CENTROAFRICANA",
    value: {
      CodigoSierp: "4",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CENTRAL AFRICAN REPUBLIC",
      label: "REPUBLICA CENTROAFRICANA",
      value: "CAF",
    },
  },
  {
    label: "REPUBLICA CHECA",
    value: {
      CodigoSierp: "378",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CZECH REPUBLIC",
      label: "REPUBLICA CHECA",
      value: "CZE",
    },
  },
  {
    label: "REPUBLICA DEL CONGO",
    value: {
      CodigoSierp: "60",
      CodigoSos: null,
      CodigoVt: null,
      Value: "REPUBLIC OF THE CONGO",
      label: "REPUBLICA DEL CONGO",
      value: "COG",
    },
  },
  {
    label: "REPUBLICA DEMOCRATICA DEL CONGO",
    value: {
      CodigoSierp: "198",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DEMOCRATIC REPUBLIC OF THE CONGO",
      label: "REPUBLICA DEMOCRATICA DEL CONGO",
      value: "COD",
    },
  },
  {
    label: "REPUBLICA DOMINICANA",
    value: {
      CodigoSierp: "199",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DOMINICAN REPUBLIC",
      label: "REPUBLICA DOMINICANA",
      value: "DOM",
    },
  },
  {
    label: "RUANDA",
    value: {
      CodigoSierp: "200",
      CodigoSos: null,
      CodigoVt: null,
      Value: "RWANDA",
      label: "RUANDA",
      value: "RWA",
    },
  },
  {
    label: "RUMANIA",
    value: {
      CodigoSierp: "201",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ROMANIA",
      label: "RUMANIA",
      value: "ROU",
    },
  },
  {
    label: "RUSIA",
    value: {
      CodigoSierp: "202",
      CodigoSos: null,
      CodigoVt: null,
      Value: "RUSSIA",
      label: "RUSIA",
      value: "RUS",
    },
  },
  {
    label: "SAHARA OCCIDENTAL",
    value: {
      CodigoSierp: "203",
      CodigoSos: null,
      CodigoVt: null,
      Value: "WESTERN SAHARA",
      label: "SAHARA OCCIDENTAL",
      value: "ESH",
    },
  },
  {
    label: "SAMOA",
    value: {
      CodigoSierp: "204",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SAMOA",
      label: "SAMOA",
      value: "WSM",
    },
  },
  {
    label: "SAMOA AMERICANA",
    value: {
      CodigoSierp: "205",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AMERICAN SAMOA",
      label: "SAMOA AMERICANA",
      value: "ASM",
    },
  },
  {
    label: "SAN CRISTOBAL Y NIEVES",
    value: {
      CodigoSierp: "206",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SAINT KITTS AND NEVIS",
      label: "SAN CRISTOBAL Y NIEVES",
      value: "KNA",
    },
  },
  {
    label: "SAN MARINO",
    value: {
      CodigoSierp: "207",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SAN MARINO",
      label: "SAN MARINO",
      value: "SMR",
    },
  },
  {
    label: "SAN PEDRO Y MIQUELON",
    value: {
      CodigoSierp: "208",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SAINT PIERRE AND MIQUELON",
      label: "SAN PEDRO Y MIQUELON",
      value: "SPM",
    },
  },
  {
    label: "SAN VICENTE Y LAS GRANADINAS",
    value: {
      CodigoSierp: "209",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SAINT VINCENT AND THE GRENADINES",
      label: "SAN VICENTE Y LAS GRANADINAS",
      value: "VCT",
    },
  },
  {
    label: "SANTA LUCIA",
    value: {
      CodigoSierp: "211",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SAINT LUCIA",
      label: "SANTA LUCIA",
      value: "LCA",
    },
  },
  {
    label: "SANTO TOME Y PRINCIPE",
    value: {
      CodigoSierp: "212",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SAO TOME AND PRINCIPE",
      label: "SANTO TOME Y PRINCIPE",
      value: "STP",
    },
  },
  {
    label: "SENEGAL",
    value: {
      CodigoSierp: "213",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SENEGAL",
      label: "SENEGAL",
      value: "SEN",
    },
  },
  {
    label: "SERBIA",
    value: {
      CodigoSierp: "214",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SERBIA",
      label: "SERBIA",
      value: "SRB",
    },
  },
  {
    label: "SEYCHELLES",
    value: {
      CodigoSierp: "215",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SEYCHELLES",
      label: "SEYCHELLES",
      value: "SYC",
    },
  },
  {
    label: "SIERRA LEONA",
    value: {
      CodigoSierp: "216",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SIERRA LEONE",
      label: "SIERRA LEONA",
      value: "SLE",
    },
  },
  {
    label: "SINGAPUR",
    value: {
      CodigoSierp: "217",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SINGAPORE",
      label: "SINGAPUR",
      value: "SGP",
    },
  },
  {
    label: "SIRIA",
    value: {
      CodigoSierp: "218",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SYRIA",
      label: "SIRIA",
      value: "SYR",
    },
  },
  {
    label: "SOMALIA",
    value: {
      CodigoSierp: "219",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOMALIA",
      label: "SOMALIA",
      value: "SOM",
    },
  },
  {
    label: "SRI LANKA",
    value: {
      CodigoSierp: "222",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SRI LANKA",
      label: "SRI LANKA",
      value: "LKA",
    },
  },
  {
    label: "SUAZILANDIA",
    value: {
      CodigoSierp: "223",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ESWATINI",
      label: "SUAZILANDIA",
      value: "SWZ",
    },
  },
  {
    label: "SUDAFRICA",
    value: {
      CodigoSierp: "224",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOUTH AFRICA",
      label: "SUDAFRICA",
      value: "ZAF",
    },
  },
  {
    label: "SUDAN",
    value: {
      CodigoSierp: "225",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUDAN",
      label: "SUDAN",
      value: "SDN",
    },
  },
  {
    label: "SUECIA",
    value: {
      CodigoSierp: "226",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SWEDEN",
      label: "SUECIA",
      value: "SWE",
    },
  },
  {
    label: "SUIZA",
    value: {
      CodigoSierp: "227",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SWITZERLAND",
      label: "SUIZA",
      value: "CHE",
    },
  },
  {
    label: "SURINAM",
    value: {
      CodigoSierp: "228",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SURINAME",
      label: "SURINAM",
      value: "SUR",
    },
  },
  {
    label: "SVALBARD Y JAN MAYEN",
    value: {
      CodigoSierp: "229",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SVALBARD AND JAN MAYEN",
      label: "SVALBARD Y JAN MAYEN",
      value: "SJM",
    },
  },
  {
    label: "TAILANDIA",
    value: {
      CodigoSierp: "230",
      CodigoSos: null,
      CodigoVt: null,
      Value: "THAILAND",
      label: "TAILANDIA",
      value: "THA",
    },
  },
  {
    label: "TAIWAN",
    value: {
      CodigoSierp: "231",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TAIWAN",
      label: "TAIWAN",
      value: "TWN",
    },
  },
  {
    label: "TANZANIA",
    value: {
      CodigoSierp: "232",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TANZANIA",
      label: "TANZANIA",
      value: "TZA",
    },
  },
  {
    label: "TAYIKISTAN",
    value: {
      CodigoSierp: "233",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TAJIKISTAN",
      label: "TAYIKISTAN",
      value: "TJK",
    },
  },
  {
    label: "TERRITORIO BRITANICO DEL OCEANO INDICO",
    value: {
      CodigoSierp: "234",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BRITISH INDIAN OCEAN TERRITORY",
      label: "TERRITORIO BRITANICO DEL OCEANO INDICO",
      value: "IOT",
    },
  },
  {
    label: "TERRITORIOS AUSTRALES FRANCESES",
    value: {
      CodigoSierp: "235",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FRENCH SOUTHERN TERRITORIES",
      label: "TERRITORIOS AUSTRALES FRANCESES",
      value: "ATF",
    },
  },
  {
    label: "TIMOR ORIENTAL",
    value: {
      CodigoSierp: "236",
      CodigoSos: null,
      CodigoVt: null,
      Value: "EAST TIMOR",
      label: "TIMOR ORIENTAL",
      value: "TLS",
    },
  },
  {
    label: "TOGO",
    value: {
      CodigoSierp: "237",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TOGO",
      label: "TOGO",
      value: "TGO",
    },
  },
  {
    label: "TOKELAU",
    value: {
      CodigoSierp: "238",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TOKELAU",
      label: "TOKELAU",
      value: "TKL",
    },
  },
  {
    label: "TONGA",
    value: {
      CodigoSierp: "239",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TONGA",
      label: "TONGA",
      value: "TON",
    },
  },
  {
    label: "TRINIDAD Y TOBAGO",
    value: {
      CodigoSierp: "240",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TRINIDAD AND TOBAGO",
      label: "TRINIDAD Y TOBAGO",
      value: "TTO",
    },
  },
  {
    label: "TUNEZ",
    value: {
      CodigoSierp: "241",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TUNISIA",
      label: "TUNEZ",
      value: "TUN",
    },
  },
  {
    label: "TURKMENISTAN",
    value: {
      CodigoSierp: "242",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TURKMENISTAN",
      label: "TURKMENISTAN",
      value: "TKM",
    },
  },
  {
    label: "TURQUIA",
    value: {
      CodigoSierp: "377",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TURKEY",
      label: "TURQUIA",
      value: "TUR",
    },
  },
  {
    label: "TUVALU",
    value: {
      CodigoSierp: "244",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TUVALU",
      label: "TUVALU",
      value: "TUV",
    },
  },
  {
    label: "UCRANIA",
    value: {
      CodigoSierp: "245",
      CodigoSos: null,
      CodigoVt: null,
      Value: "UKRAINE",
      label: "UCRANIA",
      value: "UKR",
    },
  },
  {
    label: "UGANDA",
    value: {
      CodigoSierp: "246",
      CodigoSos: null,
      CodigoVt: null,
      Value: "UGANDA",
      label: "UGANDA",
      value: "UGA",
    },
  },
  {
    label: "UNION EUROPEA",
    value: {
      CodigoSierp: "247",
      CodigoSos: null,
      CodigoVt: null,
      Value: "EUROPEAN UNION",
      label: "UNION EUROPEA",
      value: "EUR",
    },
  },
  {
    label: "URUGUAY",
    value: {
      CodigoSierp: "248",
      CodigoSos: null,
      CodigoVt: null,
      Value: "URUGUAY",
      label: "URUGUAY",
      value: "URY",
    },
  },
  {
    label: "UZBEKISTAN",
    value: {
      CodigoSierp: "249",
      CodigoSos: null,
      CodigoVt: null,
      Value: "UZBEKISTAN",
      label: "UZBEKISTAN",
      value: "UZB",
    },
  },
  {
    label: "VANUATU",
    value: {
      CodigoSierp: "250",
      CodigoSos: null,
      CodigoVt: null,
      Value: "VANUATU",
      label: "VANUATU",
      value: "VUT",
    },
  },
  {
    label: "VENEZUELA",
    value: {
      CodigoSierp: "6",
      CodigoSos: null,
      CodigoVt: null,
      Value: "VENEZUELA",
      label: "VENEZUELA",
      value: "VEN",
    },
  },
  {
    label: "VIETNAM",
    value: {
      CodigoSierp: "251",
      CodigoSos: null,
      CodigoVt: null,
      Value: "VIETNAM",
      label: "VIETNAM",
      value: "VNM",
    },
  },
  {
    label: "WALLIS Y FUTUNA",
    value: {
      CodigoSierp: "253",
      CodigoSos: null,
      CodigoVt: null,
      Value: "WALLIS AND FUTUNA",
      label: "WALLIS Y FUTUNA",
      value: "WLF",
    },
  },
  {
    label: "YEMEN",
    value: {
      CodigoSierp: "255",
      CodigoSos: null,
      CodigoVt: null,
      Value: "YEMEN",
      label: "YEMEN",
      value: "YEM",
    },
  },
  {
    label: "YIBUTI",
    value: {
      CodigoSierp: "256",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DJIBOUTI",
      label: "YIBUTI",
      value: "DJI",
    },
  },
  {
    label: "ZAMBIA",
    value: {
      CodigoSierp: "257",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ZAMBIA",
      label: "ZAMBIA",
      value: "ZMB",
    },
  },
  {
    label: "ZIMBABUE",
    value: {
      CodigoSierp: "258",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ZIMBABWE",
      label: "ZIMBABUE",
      value: "ZWE",
    },
  },
];

export { listNacionalidadFormsWeb };
