const listRamoFormsWeb = [
  {
    label: "ACCIDENTES PERSONALES",
    value: {
      CodigoSierp: "3",
      CodigoSos:
        "SOS(AP), SOS(BG), SOS(BP), SOS(AA), SOS(BM), SOS(BX), SOS(BS), SOS(BL), SOS(BK), SOS(BE), SOS(AE), SOS(BZ), SOS(BC), SOS(BB)",
      CodigoVt: "110",
      Value: "PERSONAL ACCIDENTS",
      label: "ACCIDENTES PERSONALES",
      value: "4",
    },
  },
  {
    label: "AVIACION",
    value: {
      CodigoSierp: "26",
      CodigoSos: "SOS(CA)",
      CodigoVt: "100",
      Value: "AVIATION",
      label: "AVIACION",
      value: "10",
    },
  },
  {
    label: "BANCOS E INSTITUCIONES FINANCIERAS",
    value: {
      CodigoSierp: "24",
      CodigoSos: "SOS(BF)",
      CodigoVt: "120",
      Value: "BANKS AND FINANCIAL INSTITUTIONS",
      label: "BANCOS E INSTITUCIONES FINANCIERAS",
      value: "24",
    },
  },
  {
    label: "BUEN USO DE ANTICIPO",
    value: {
      CodigoSierp: "6",
      CodigoSos: "SOS(BA)",
      CodigoVt: "132",
      Value: "PROPER USE OF ADVANCE PAYMENT",
      label: "BUEN USO DE ANTICIPO",
      value: "28",
    },
  },
  {
    label: "COLECTIVO VIDA",
    value: {
      CodigoSierp: "30",
      CodigoSos: "SOS(CV)",
      CodigoVt: "3",
      Value: "GROUP LIFE",
      label: "COLECTIVO VIDA",
      value: "2",
    },
  },
  {
    label: "CUMPLIMIENTO DE CONTRATO",
    value: {
      CodigoSierp: "5",
      CodigoSos: "SOS(CU)",
      CodigoVt: "131",
      Value: "CONTRACT COMPLIANCE",
      label: "CUMPLIMIENTO DE CONTRATO",
      value: "27",
    },
  },
  {
    label: "DINERO Y VALORES",
    value: {
      CodigoSierp: "12",
      CodigoSos: "SOS(DV)",
      CodigoVt: "140",
      Value: "MONEY AND SECURITIES",
      label: "DINERO Y VALORES",
      value: "12",
    },
  },
  {
    label: "EJECUCION DE OBRA Y BUENA CALIDAD DE MATERIALES",
    value: {
      CodigoSierp: "7",
      CodigoSos: "SOS(CM)",
      CodigoVt: "134",
      Value: "WORK EXECUTION AND GOOD QUALITY OF MATERIALS",
      label: "EJECUCION DE OBRA Y BUENA CALIDAD DE MATERIALES",
      value: "29",
    },
  },
  {
    label: "EQUIPO ELECTRONICO",
    value: {
      CodigoSierp: "11",
      CodigoSos: "SOS(EE), SOS(EQ) ",
      CodigoVt: "210",
      Value: "ELECTRONIC EQUIPMENT",
      label: "EQUIPO ELECTRONICO",
      value: "20",
    },
  },
  {
    label: "EQUIPO Y MAQUINARIA DE CONTRATISTAS",
    value: {
      CodigoSierp: "13",
      CodigoSos: "SOS(EM)",
      CodigoVt: "170",
      Value: "CONTRACTORS' EQUIPMENT AND MACHINERY",
      label: "EQUIPO Y MAQUINARIA DE CONTRATISTAS",
      value: "18",
    },
  },
  {
    label: "FIDELIDAD PUBLICO Y PRIVADO",
    value: {
      CodigoSierp: "18",
      CodigoSos: "SOS(FD), SOS(FP)",
      CodigoVt: "130",
      Value: "PUBLIC AND PRIVATE FIDELITY",
      label: "FIDELIDAD PUBLICO Y PRIVADO",
      value: "22",
    },
  },
  {
    label: "GARANTIAS ADUANERAS",
    value: {
      CodigoSierp: "8",
      CodigoSos: "SOS(GA)",
      CodigoVt: "136",
      Value: "CUSTOMS GUARANTEES",
      label: "GARANTIAS ADUANERAS",
      value: "31",
    },
  },
  {
    label: "INCENDIO Y LINEAS ALIADAS",
    value: {
      CodigoSierp: "2",
      CodigoSos: "SOS(IN)",
      CodigoVt: "78",
      Value: "FIRE AND ALLIED LINES",
      label: "INCENDIO Y LINEAS ALIADAS",
      value: "5",
    },
  },
  {
    label: "INDIVIDUAL VIDA",
    value: {
      CodigoSierp: "36",
      CodigoSos: "SOS(IV)",
      CodigoVt: "2",
      Value: "INDIVIDUAL LIFE",
      label: "INDIVIDUAL VIDA",
      value: "1",
    },
  },
  {
    label: "LUCRO CESANTE A CONSECUENCIA DE INCENDIO Y LINEAS ALIADAS",
    value: {
      CodigoSierp: "22",
      CodigoSos: "SOS(LC)",
      CodigoVt: "220",
      Value: "BUSINESS INTERRUPTION DUE TO FIRE AND ALLIED LINES",
      label: "LUCRO CESANTE A CONSECUENCIA DE INCENDIO Y LINEAS ALIADAS",
      value: "6",
    },
  },
  {
    label: "LUCRO CESANTE A CONSECUENCIA DE RIESGOS CATASTROFICOS",
    value: {
      CodigoSierp: null,
      CodigoSos: null,
      CodigoVt: null,
      Value: "BUSINESS INTERRUPTION DUE TO CATASTROPHIC RISKS",
      label: "LUCRO CESANTE A CONSECUENCIA DE RIESGOS CATASTROFICOS",
      value: "42",
    },
  },
  {
    label: "LUCRO CESANTE POR ROTURA",
    value: {
      CodigoSierp: "23",
      CodigoSos: null,
      CodigoVt: "230",
      Value: "BUSINESS INTERRUPTION DUE TO BREAKDOWN",
      label: "LUCRO CESANTE POR ROTURA",
      value: "44",
    },
  },
  {
    label: "MARITIMO",
    value: {
      CodigoSierp: "27",
      CodigoSos: "SOS(CB)",
      CodigoVt: "40",
      Value: "MARINE",
      label: "MARITIMO",
      value: "9",
    },
  },
  {
    label: "MONTAJE DE MAQUINARIA",
    value: {
      CodigoSierp: "17",
      CodigoSos: "SOS(MM)",
      CodigoVt: "150",
      Value: "MACHINERY ERECTION",
      label: "MONTAJE DE MAQUINARIA",
      value: "15",
    },
  },
  {
    label: "MULTIRIESGO",
    value: {
      CodigoSierp: "19",
      CodigoSos: "SOS(MI),SOS(MC)",
      CodigoVt: "21",
      Value: "MULTIRISK",
      label: "MULTIRIESGO",
      value: "40",
    },
  },
  {
    label: "OBRAS CIVILES TERMINADAS",
    value: {
      CodigoSierp: "34",
      CodigoSos: "SOS(OC)",
      CodigoVt: "200",
      Value: "COMPLETED CIVIL WORKS",
      label: "OBRAS CIVILES TERMINADAS",
      value: "19",
    },
  },
  {
    label: "OTRAS GARANTIAS",
    value: {
      CodigoSierp: "29",
      CodigoSos: "SOS(GT)",
      CodigoVt: "135",
      Value: "OTHER GUARANTEES",
      label: "OTRAS GARANTIAS",
      value: "33",
    },
  },
  {
    label: "PERDIDA DE BENEFICIO POR ROTURA DE MAQUINARIA",
    value: {
      CodigoSierp: "23",
      CodigoSos: "SOS(LR)",
      CodigoVt: "230",
      Value: "BUSINESS INTERRUPTION DUE TO MACHINERY BREAKDOWN",
      label: "PERDIDA DE BENEFICIO POR ROTURA DE MAQUINARIA",
      value: "17",
    },
  },
  {
    label: "PROGRAMA DE SEGUROS",
    value: {
      CodigoSierp: "9",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INSURANCE PROGRAM",
      label: "PROGRAMA DE SEGUROS",
      value: "43",
    },
  },
  {
    label: "RESPONSABILIDAD CIVIL",
    value: {
      CodigoSierp: "14",
      CodigoSos: "SOS(RC), SOS(RD), SOS(RP), SOS(RT),SOS(RO)",
      CodigoVt: "180",
      Value: "CIVIL LIABILITY",
      label: "RESPONSABILIDAD CIVIL",
      value: "21",
    },
  },
  {
    label: "RIESGOS CATASTROFICOS",
    value: {
      CodigoSierp: null,
      CodigoSos: null,
      CodigoVt: null,
      Value: "CATASTROPHIC RISKS",
      label: "RIESGOS CATASTROFICOS",
      value: "41",
    },
  },
  {
    label: "RIESGOS ESPECIALES",
    value: {
      CodigoSierp: "24",
      CodigoSos: "SOS(RE)",
      CodigoVt: "20",
      Value: "SPECIAL RISKS",
      label: "RIESGOS ESPECIALES",
      value: "26",
    },
  },
  {
    label: "ROBO",
    value: {
      CodigoSierp: "10",
      CodigoSos: "SOS(RB)",
      CodigoVt: "12",
      Value: "THEFT",
      label: "ROBO",
      value: "11",
    },
  },
  {
    label: "ROTURA DE MAQUINARIA",
    value: {
      CodigoSierp: "21",
      CodigoSos: "SOS(RM) ",
      CodigoVt: "60",
      Value: "MACHINERY BREAKDOWN",
      label: "ROTURA DE MAQUINARIA",
      value: "16",
    },
  },
  {
    label: "SERIEDAD DE OFERTA",
    value: {
      CodigoSierp: "4",
      CodigoSos: "SOS(SO) ",
      CodigoVt: "133",
      Value: "BID BOND",
      label: "SERIEDAD DE OFERTA",
      value: "23",
    },
  },
  {
    label: "TODO RIESGO PARA CONTRATISTAS",
    value: {
      CodigoSierp: "35",
      CodigoSos: "SOS(TC)",
      CodigoVt: "190",
      Value: "ALL RISK FOR CONTRACTORS",
      label: "TODO RIESGO PARA CONTRATISTAS",
      value: "14",
    },
  },
  {
    label: "TODO RIESGO PETROLERO",
    value: {
      CodigoSierp: "39",
      CodigoSos: "SOS(PR)",
      CodigoVt: "190",
      Value: "ALL RISK PETROLEUM",
      label: "TODO RIESGO PETROLERO",
      value: "38",
    },
  },
  {
    label: "TRANSPORTE",
    value: {
      CodigoSierp: "15",
      CodigoSos: "SOS(TR), SOS(TN), SOS(TT), SOS(TA), SOS(TM)",
      CodigoVt: "14",
      Value: "TRANSPORT",
      label: "TRANSPORTE",
      value: "8",
    },
  },
  {
    label: "VEHICULOS",
    value: {
      CodigoSierp: "1",
      CodigoSos:
        "SOS(VH), SOS(VK), SOS(VC), SOS(VJ), SOS(VU), SOS(VA), SOS(VF), SOS(VE), SOS(VO), SOS(VD), SOS(VT), SOS(VS), SOS(VR), SOS(VP), SOS(VM), SOS(VL), SOS(VI), SOS(VG), SOS(VB), SOS(TX), SOS(VX)",
      CodigoVt: "6",
      Value: "VEHICLES",
      label: "VEHICULOS",
      value: "7",
    },
  },
];

export { listRamoFormsWeb };
