const listProfesionFormsWeb = [
  {
    label: "ABOGADO",
    value: {
      CodigoSierp: "108",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LAWYER",
      label: "ABOGADO",
      value: "1",
    },
  },
  {
    label: "ADMINISTRACION",
    value: {
      CodigoSierp: "171",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ADMINISTRATION",
      label: "ADMINISTRACION",
      value: "2",
    },
  },
  {
    label: "ARQUITECTO",
    value: {
      CodigoSierp: "107",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ARCHITECT",
      label: "ARQUITECTO",
      value: "3",
    },
  },
  {
    label:
      "ASISTENTE EN EDUCACION INCLUSIVA CON NIVEL EQUIVALENTE A TECNOLOGO",
    value: {
      CodigoSierp: "204",
      CodigoSos: null,
      CodigoVt: null,
      Value:
        "INCLUSIVE EDUCATION ASSISTANT WITH EQUIVALENT LEVEL TO TECHNOLOGIST",
      label:
        "ASISTENTE EN EDUCACION INCLUSIVA CON NIVEL EQUIVALENTE A TECNOLOGO",
      value: "4",
    },
  },
  {
    label: "BIBLIOTECARIO",
    value: {
      CodigoSierp: "112",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LIBRARIAN",
      label: "BIBLIOTECARIO",
      value: "5",
    },
  },
  {
    label: "BIOLOGO",
    value: {
      CodigoSierp: "205",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BIOLOGIST",
      label: "BIOLOGO",
      value: "6",
    },
  },
  {
    label: "BIOQUIMICO",
    value: {
      CodigoSierp: "113",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BIOCHEMIST",
      label: "BIOQUIMICO",
      value: "7",
    },
  },
  {
    label: "BIOQUIMICO FARMACEUTICA",
    value: {
      CodigoSierp: "206",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PHARMACEUTICAL BIOCHEMIST",
      label: "BIOQUIMICO FARMACEUTICA",
      value: "8",
    },
  },
  {
    label: "CARABINERO",
    value: {
      CodigoSierp: "115",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CARABINIER",
      label: "CARABINERO",
      value: "9",
    },
  },
  {
    label: "CRIMINALISTICA",
    value: {
      CodigoSierp: "207",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CRIMINALISTICS",
      label: "CRIMINALISTICA",
      value: "10",
    },
  },
  {
    label: "CUIDADOS PERSONALES Y ESTETICA",
    value: {
      CodigoSierp: "208",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PERSONAL CARE AND ESTHETICS",
      label: "CUIDADOS PERSONALES Y ESTETICA",
      value: "11",
    },
  },
  {
    label: "DIPLOMATICO",
    value: {
      CodigoSierp: "119",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DIPLOMAT",
      label: "DIPLOMATICO",
      value: "12",
    },
  },
  {
    label: "DIRECTOR TECNICO EN DEPORTES CON NIVEL EQUIVALENTE A TECNOLOGO",
    value: {
      CodigoSierp: "209",
      CodigoSos: null,
      CodigoVt: null,
      Value:
        "TECHNICAL DIRECTOR IN SPORTS WITH EQUIVALENT LEVEL TO TECHNOLOGIST",
      label: "DIRECTOR TECNICO EN DEPORTES CON NIVEL EQUIVALENTE A TECNOLOGO",
      value: "13",
    },
  },
  {
    label: "ECONOMISTA",
    value: {
      CodigoSierp: "210",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ECONOMIST",
      label: "ECONOMISTA",
      value: "14",
    },
  },
  {
    label: "EDUCACION MILITAR",
    value: {
      CodigoSierp: "127",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MILITARY EDUCATION",
      label: "EDUCACION MILITAR",
      value: "15",
    },
  },
  {
    label: "EDUCACION PARVULARIA",
    value: {
      CodigoSierp: "122",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PRESCHOOL EDUCATION",
      label: "EDUCACION PARVULARIA",
      value: "16",
    },
  },
  {
    label: "FISICO",
    value: {
      CodigoSierp: "211",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PHYSICIST",
      label: "FISICO",
      value: "17",
    },
  },
  {
    label: "FUTBOLISTA PROFESIONAL",
    value: {
      CodigoSierp: "126",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PROFESSIONAL FOOTBALL PLAYER",
      label: "FUTBOLISTA PROFESIONAL",
      value: "18",
    },
  },
  {
    label: "GEOLOGO",
    value: {
      CodigoSierp: "128",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GEOLOGIST",
      label: "GEOLOGO",
      value: "19",
    },
  },
  {
    label:
      "GESTOR DE EVENTOS, FERIAS Y CONVENCIONES CON NIVEL EQUIVALENTE A TECNICO",
    value: {
      CodigoSierp: "212",
      CodigoSos: null,
      CodigoVt: null,
      Value:
        "EVENT, FAIR, AND CONVENTION MANAGER WITH EQUIVALENT LEVEL TO TECHNICIAN",
      label:
        "GESTOR DE EVENTOS, FERIAS Y CONVENCIONES CON NIVEL EQUIVALENTE A TECNICO",
      value: "20",
    },
  },
  {
    label: "GRAFOLOGO",
    value: {
      CodigoSierp: "213",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRAPHOLOGIST",
      label: "GRAFOLOGO",
      value: "21",
    },
  },
  {
    label: "GUIA NACIONAL DE TURISMO",
    value: {
      CodigoSierp: "214",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NATIONAL TOURISM GUIDE",
      label: "GUIA NACIONAL DE TURISMO",
      value: "22",
    },
  },
  {
    label: "INGENIERIA EN ENERGIAS RENOVABLES",
    value: {
      CodigoSierp: "215",
      CodigoSos: null,
      CodigoVt: null,
      Value: "RENEWABLE ENERGY ENGINEERING",
      label: "INGENIERIA EN ENERGIAS RENOVABLES",
      value: "23",
    },
  },
  {
    label: "INGENIERO ACUICOLA",
    value: {
      CodigoSierp: "217",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AQUACULTURE ENGINEER",
      label: "INGENIERO ACUICOLA",
      value: "25",
    },
  },
  {
    label: "INGENIERO AERONAUTICO",
    value: {
      CodigoSierp: "218",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AERONAUTICAL ENGINEER",
      label: "INGENIERO AERONAUTICO",
      value: "26",
    },
  },
  {
    label: "INGENIERO AGRICOLA",
    value: {
      CodigoSierp: "219",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AGRICULTURAL ENGINEER",
      label: "INGENIERO AGRICOLA",
      value: "27",
    },
  },
  {
    label: "INGENIERO AGROINDUSTRIAL",
    value: {
      CodigoSierp: "220",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AGROINDUSTRIAL ENGINEER",
      label: "INGENIERO AGROINDUSTRIAL",
      value: "28",
    },
  },
  {
    label: "INGENIERO AGRONOMO",
    value: {
      CodigoSierp: "129",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AGRONOMICAL ENGINEER",
      label: "INGENIERO AGRONOMO",
      value: "29",
    },
  },
  {
    label: "INGENIERO AGROPECUARIO",
    value: {
      CodigoSierp: "221",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LIVESTOCK ENGINEER",
      label: "INGENIERO AGROPECUARIO",
      value: "30",
    },
  },
  {
    label: "INGENIERO AMBIENTAL",
    value: {
      CodigoSierp: "222",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ENVIRONMENTAL ENGINEER",
      label: "INGENIERO AMBIENTAL",
      value: "31",
    },
  },
  {
    label: "INGENIERO AUTOMOTRIZ",
    value: {
      CodigoSierp: "223",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AUTOMOTIVE ENGINEER",
      label: "INGENIERO AUTOMOTRIZ",
      value: "32",
    },
  },
  {
    label: "INGENIERO BIOMEDICO",
    value: {
      CodigoSierp: "224",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BIOMEDICAL ENGINEER",
      label: "INGENIERO BIOMEDICO",
      value: "33",
    },
  },
  {
    label: "INGENIERO BIOMOLECULAR Y BIOCOMBUSTIBLES",
    value: {
      CodigoSierp: "225",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BIOMOLECULAR AND BIOFUELS ENGINEER",
      label: "INGENIERO BIOMOLECULAR Y BIOCOMBUSTIBLES",
      value: "34",
    },
  },
  {
    label: "INGENIERO BIOTECNOLOGO",
    value: {
      CodigoSierp: "226",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BIOTECHNOLOGIST ENGINEER",
      label: "INGENIERO BIOTECNOLOGO",
      value: "35",
    },
  },
  {
    label: "INGENIERO CIVIL",
    value: {
      CodigoSierp: "130",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CIVIL ENGINEER",
      label: "INGENIERO CIVIL",
      value: "36",
    },
  },
  {
    label: "INGENIERO COMERCIAL",
    value: {
      CodigoSierp: "136",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COMMERCIAL ENGINEER",
      label: "INGENIERO COMERCIAL",
      value: "37",
    },
  },
  {
    label: "INGENIERO COMPUTACION GRAFICA",
    value: {
      CodigoSierp: "227",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRAPHIC COMPUTING ENGINEER",
      label: "INGENIERO COMPUTACION GRAFICA",
      value: "38",
    },
  },
  {
    label: "INGENIERO DE POLIMEROS",
    value: {
      CodigoSierp: "228",
      CodigoSos: null,
      CodigoVt: null,
      Value: "POLYMER ENGINEER",
      label: "INGENIERO DE POLIMEROS",
      value: "39",
    },
  },
  {
    label: "INGENIERO DE SOFTWARE",
    value: {
      CodigoSierp: "216",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOFTWARE ENGINEER",
      label: "INGENIERO DE SOFTWARE",
      value: "24",
    },
  },
  {
    label: "INGENIERO ELECTRICO",
    value: {
      CodigoSierp: "138",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ELECTRICAL ENGINEER",
      label: "INGENIERO ELECTRICO",
      value: "40",
    },
  },
  {
    label: "INGENIERO ELECTROMECANICO",
    value: {
      CodigoSierp: "229",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ELECTROMECHANICAL ENGINEER",
      label: "INGENIERO ELECTROMECANICO",
      value: "41",
    },
  },
  {
    label: "INGENIERO EN ALIMENTOS",
    value: {
      CodigoSierp: "230",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FOOD ENGINEER",
      label: "INGENIERO EN ALIMENTOS",
      value: "42",
    },
  },
  {
    label: "INGENIERO EN BIODIVERSIDAD Y RECURSOS GENETICOS",
    value: {
      CodigoSierp: "231",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BIODIVERSITY AND GENETIC RESOURCES ENGINEER",
      label: "INGENIERO EN BIODIVERSIDAD Y RECURSOS GENETICOS",
      value: "43",
    },
  },
  {
    label: "INGENIERO EN CIENCIAS DE LA COMPUTACION",
    value: {
      CodigoSierp: "133",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COMPUTER SCIENCE ENGINEER",
      label: "INGENIERO EN CIENCIAS DE LA COMPUTACION",
      value: "44",
    },
  },
  {
    label: "INGENIERO EN CIENCIAS DEL AGUA",
    value: {
      CodigoSierp: "232",
      CodigoSos: null,
      CodigoVt: null,
      Value: "WATER SCIENCE ENGINEER",
      label: "INGENIERO EN CIENCIAS DEL AGUA",
      value: "45",
    },
  },
  {
    label: "INGENIERO EN COMERCIO ELECTRONICO",
    value: {
      CodigoSierp: "233",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ELECTRONIC COMMERCE ENGINEER",
      label: "INGENIERO EN COMERCIO ELECTRONICO",
      value: "46",
    },
  },
  {
    label: "INGENIERO EN COMPUTACION",
    value: {
      CodigoSierp: "140",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COMPUTING ENGINEER",
      label: "INGENIERO EN COMPUTACION",
      value: "47",
    },
  },
  {
    label: "INGENIERO EN DISEÑO INDUSTRIAL Y DE PROCESOS",
    value: {
      CodigoSierp: "142",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INDUSTRIAL AND PROCESS DESIGN ENGINEER",
      label: "INGENIERO EN DISEÑO INDUSTRIAL Y DE PROCESOS",
      value: "48",
    },
  },
  {
    label: "INGENIERO EN ELECTRONICA",
    value: {
      CodigoSierp: "139",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ELECTRONICS ENGINEER",
      label: "INGENIERO EN ELECTRONICA",
      value: "49",
    },
  },
  {
    label: "INGENIERO EN ELECTRONICA Y AUTOMATIZACION",
    value: {
      CodigoSierp: "234",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ELECTRONICS AND AUTOMATION ENGINEER",
      label: "INGENIERO EN ELECTRONICA Y AUTOMATIZACION",
      value: "50",
    },
  },
  {
    label: "INGENIERO EN GEOTECNIA",
    value: {
      CodigoSierp: "235",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GEOTECHNICAL ENGINEER",
      label: "INGENIERO EN GEOTECNIA",
      value: "51",
    },
  },
  {
    label: "INGENIERO EN HIDRAULICA",
    value: {
      CodigoSierp: "236",
      CodigoSos: null,
      CodigoVt: null,
      Value: "HYDRAULIC ENGINEER",
      label: "INGENIERO EN HIDRAULICA",
      value: "52",
    },
  },
  {
    label: "INGENIERO EN LOGISTICA Y TRANSPORTE",
    value: {
      CodigoSierp: "237",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LOGISTICS AND TRANSPORTATION ENGINEER",
      label: "INGENIERO EN LOGISTICA Y TRANSPORTE",
      value: "53",
    },
  },
  {
    label: "INGENIERO EN MANTENIMIENTO INDUSTRIAL",
    value: {
      CodigoSierp: "238",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INDUSTRIAL MAINTENANCE ENGINEER",
      label: "INGENIERO EN MANTENIMIENTO INDUSTRIAL",
      value: "54",
    },
  },
  {
    label: "INGENIERO EN MATERIALES",
    value: {
      CodigoSierp: "239",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MATERIALS ENGINEER",
      label: "INGENIERO EN MATERIALES",
      value: "55",
    },
  },
  {
    label: "INGENIERO EN MECATRONICA",
    value: {
      CodigoSierp: "240",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MECHATRONICAL ENGINEER",
      label: "INGENIERO EN MECATRONICA",
      value: "56",
    },
  },
  {
    label: "INGENIERO EN METALURGIA",
    value: {
      CodigoSierp: "241",
      CodigoSos: null,
      CodigoVt: null,
      Value: "METALLURGICAL ENGINEER",
      label: "INGENIERO EN METALURGIA",
      value: "57",
    },
  },
  {
    label: "INGENIERO EN MINAS",
    value: {
      CodigoSierp: "145",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MINING ENGINEER",
      label: "INGENIERO EN MINAS",
      value: "58",
    },
  },
  {
    label: "INGENIERO EN NANOTECNOLOGIA",
    value: {
      CodigoSierp: "242",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NANOTECHNOLOGY ENGINEER",
      label: "INGENIERO EN NANOTECNOLOGIA",
      value: "59",
    },
  },
  {
    label: "INGENIERO EN PETROLEOS",
    value: {
      CodigoSierp: "243",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PETROLEUM ENGINEER",
      label: "INGENIERO EN PETROLEOS",
      value: "60",
    },
  },
  {
    label: "INGENIERO EN PRODUCCION Y OPERACIONES",
    value: {
      CodigoSierp: "244",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PRODUCTION AND OPERATIONS ENGINEER",
      label: "INGENIERO EN PRODUCCION Y OPERACIONES",
      value: "61",
    },
  },
  {
    label: "INGENIERO EN RECURSOS NATURALES RENOVABLES",
    value: {
      CodigoSierp: "245",
      CodigoSos: null,
      CodigoVt: null,
      Value: "RENEWABLE NATURAL RESOURCES ENGINEER",
      label: "INGENIERO EN RECURSOS NATURALES RENOVABLES",
      value: "62",
    },
  },
  {
    label: "INGENIERO EN SEGURIDAD INDUSTRIAL",
    value: {
      CodigoSierp: "246",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INDUSTRIAL SAFETY ENGINEER",
      label: "INGENIERO EN SEGURIDAD INDUSTRIAL",
      value: "63",
    },
  },
  {
    label: "INGENIERO EN SISTEMAS DE INFORMACION",
    value: {
      CodigoSierp: "106",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INFORMATION SYSTEMS ENGINEER",
      label: "INGENIERO EN SISTEMAS DE INFORMACION",
      value: "64",
    },
  },
  {
    label: "INGENIERO EN SONIDO Y ACUSTICA",
    value: {
      CodigoSierp: "247",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOUND AND ACOUSTICS ENGINEER",
      label: "INGENIERO EN SONIDO Y ACUSTICA",
      value: "65",
    },
  },
  {
    label: "INGENIERO EN TECNOLOGIAS DE LA INFORMACION",
    value: {
      CodigoSierp: "141",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INFORMATION TECHNOLOGY ENGINEER",
      label: "INGENIERO EN TECNOLOGIAS DE LA INFORMACION",
      value: "66",
    },
  },
  {
    label: "INGENIERO EN TECNOLOGIAS NUCLEARES Y ENERGETICAS",
    value: {
      CodigoSierp: "248",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NUCLEAR AND ENERGY TECHNOLOGY ENGINEER",
      label: "INGENIERO EN TECNOLOGIAS NUCLEARES Y ENERGETICAS",
      value: "67",
    },
  },
  {
    label: "INGENIERO EN TELECOMUNICACIONES",
    value: {
      CodigoSierp: "249",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TELECOMMUNICATIONS ENGINEER",
      label: "INGENIERO EN TELECOMUNICACIONES",
      value: "68",
    },
  },
  {
    label: "INGENIERO EN TELEMATICA",
    value: {
      CodigoSierp: "250",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TELEMATICS ENGINEER",
      label: "INGENIERO EN TELEMATICA",
      value: "69",
    },
  },
  {
    label: "INGENIERO ESTADISTICO",
    value: {
      CodigoSierp: "251",
      CodigoSos: null,
      CodigoVt: null,
      Value: "STATISTICAL ENGINEER",
      label: "INGENIERO ESTADISTICO",
      value: "70",
    },
  },
  {
    label: "INGENIERO FISICO",
    value: {
      CodigoSierp: "252",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PHYSICAL ENGINEER",
      label: "INGENIERO FISICO",
      value: "71",
    },
  },
  {
    label: "INGENIERO FORESTAL",
    value: {
      CodigoSierp: "144",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FOREST ENGINEER",
      label: "INGENIERO FORESTAL",
      value: "72",
    },
  },
  {
    label: "INGENIERO GENETICO",
    value: {
      CodigoSierp: "253",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GENETIC ENGINEER",
      label: "INGENIERO GENETICO",
      value: "73",
    },
  },
  {
    label: "INGENIERO GEOGRAFO",
    value: {
      CodigoSierp: "254",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GEOGRAPHER",
      label: "INGENIERO GEOGRAFO",
      value: "74",
    },
  },
  {
    label: "INGENIERO GEOLOGO",
    value: {
      CodigoSierp: "255",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GEOLOGIST",
      label: "INGENIERO GEOLOGO",
      value: "75",
    },
  },
  {
    label: "INGENIERO HIDROLOGO",
    value: {
      CodigoSierp: "256",
      CodigoSos: null,
      CodigoVt: null,
      Value: "HYDROLOGICAL ENGINEER",
      label: "INGENIERO HIDROLOGO",
      value: "76",
    },
  },
  {
    label: "INGENIERO INDUSTRIAL",
    value: {
      CodigoSierp: "135",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INDUSTRIAL ENGINEER",
      label: "INGENIERO INDUSTRIAL",
      value: "77",
    },
  },
  {
    label: "INGENIERO INFORMATICO",
    value: {
      CodigoSierp: "134",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COMPUTER ENGINEER",
      label: "INGENIERO INFORMATICO",
      value: "78",
    },
  },
  {
    label: "INGENIERO MATEMATICO",
    value: {
      CodigoSierp: "257",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MATHEMATICAL ENGINEER",
      label: "INGENIERO MATEMATICO",
      value: "79",
    },
  },
  {
    label: "INGENIERO MECANICO",
    value: {
      CodigoSierp: "258",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MECHANICAL ENGINEER",
      label: "INGENIERO MECANICO",
      value: "80",
    },
  },
  {
    label: "INGENIERO METEOROLOGO",
    value: {
      CodigoSierp: "259",
      CodigoSos: null,
      CodigoVt: null,
      Value: "METEOROLOGIST",
      label: "INGENIERO METEOROLOGO",
      value: "81",
    },
  },
  {
    label: "INGENIERO NAVAL",
    value: {
      CodigoSierp: "260",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NAVAL ENGINEER",
      label: "INGENIERO NAVAL",
      value: "82",
    },
  },
  {
    label: "INGENIERO OCEANOGRAFICO",
    value: {
      CodigoSierp: "261",
      CodigoSos: null,
      CodigoVt: null,
      Value: "OCEANOGRAPHIC ENGINEER",
      label: "INGENIERO OCEANOGRAFICO",
      value: "83",
    },
  },
  {
    label: "INGENIERO QUIMICO",
    value: {
      CodigoSierp: "262",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CHEMICAL ENGINEER",
      label: "INGENIERO QUIMICO",
      value: "84",
    },
  },
  {
    label: "INGENIERO TEXTIL",
    value: {
      CodigoSierp: "263",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TEXTILE ENGINEER",
      label: "INGENIERO TEXTIL",
      value: "85",
    },
  },
  {
    label: "INGENIERO ZOOTECNISTA",
    value: {
      CodigoSierp: "264",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ANIMAL SCIENCE ENGINEER",
      label: "INGENIERO ZOOTECNISTA",
      value: "86",
    },
  },
  {
    label: "LICENCIADO EN ACTIVIDAD FISICA",
    value: {
      CodigoSierp: "267",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PHYSICAL ACTIVITY",
      label: "LICENCIADO EN ACTIVIDAD FISICA",
      value: "90",
    },
  },
  {
    label: "LICENCIADO EN ADMINISTRACION DE EMPRESAS",
    value: {
      CodigoSierp: "137",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN BUSINESS ADMINISTRATION",
      label: "LICENCIADO EN ADMINISTRACION DE EMPRESAS",
      value: "91",
    },
  },
  {
    label: "LICENCIADO EN ADMINISTRACION PUBLICA",
    value: {
      CodigoSierp: "268",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PUBLIC ADMINISTRATION",
      label: "LICENCIADO EN ADMINISTRACION PUBLICA",
      value: "92",
    },
  },
  {
    label: "LICENCIADO EN ANIMACION DIGITAL",
    value: {
      CodigoSierp: "269",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN DIGITAL ANIMATION",
      label: "LICENCIADO EN ANIMACION DIGITAL",
      value: "93",
    },
  },
  {
    label: "LICENCIADO EN ANTROPOLOGIA",
    value: {
      CodigoSierp: "270",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN ANTHROPOLOGY",
      label: "LICENCIADO EN ANTROPOLOGIA",
      value: "94",
    },
  },
  {
    label: "LICENCIADO EN ARQUEOLOGIA",
    value: {
      CodigoSierp: "271",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN ARCHEOLOGY",
      label: "LICENCIADO EN ARQUEOLOGIA",
      value: "95",
    },
  },
  {
    label: "LICENCIADO EN ARTES ESCENICAS",
    value: {
      CodigoSierp: "272",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PERFORMING ARTS",
      label: "LICENCIADO EN ARTES ESCENICAS",
      value: "96",
    },
  },
  {
    label: "LICENCIADO EN ARTES LIBERALES",
    value: {
      CodigoSierp: "104",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN LIBERAL ARTS",
      label: "LICENCIADO EN ARTES LIBERALES",
      value: "97",
    },
  },
  {
    label: "LICENCIADO EN ARTES MUSICALES",
    value: {
      CodigoSierp: "151",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN MUSICAL ARTS",
      label: "LICENCIADO EN ARTES MUSICALES",
      value: "98",
    },
  },
  {
    label: "LICENCIADO EN ARTES PLASTICAS",
    value: {
      CodigoSierp: "273",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN VISUAL ARTS",
      label: "LICENCIADO EN ARTES PLASTICAS",
      value: "99",
    },
  },
  {
    label: "LICENCIADO EN ATENCION PRIMARIA DE SALUD",
    value: {
      CodigoSierp: "274",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PRIMARY HEALTH CARE",
      label: "LICENCIADO EN ATENCION PRIMARIA DE SALUD",
      value: "100",
    },
  },
  {
    label: "LICENCIADO EN AUDITORIA Y CONTROL DE GESTION",
    value: {
      CodigoSierp: "266",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN AUDITING AND MANAGEMENT CONTROL",
      label: "LICENCIADO EN AUDITORIA Y CONTROL DE GESTION",
      value: "88",
    },
  },
  {
    label: "LICENCIADO EN BACTERIOLOGIA",
    value: {
      CodigoSierp: "275",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN BACTERIOLOGY",
      label: "LICENCIADO EN BACTERIOLOGIA",
      value: "101",
    },
  },
  {
    label: "LICENCIADO EN BIBLIOTECOLOGIA, DOCUMENTACION Y ARCHIVO",
    value: {
      CodigoSierp: "276",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN LIBRARY SCIENCE, DOCUMENTATION, AND ARCHIVE",
      label: "LICENCIADO EN BIBLIOTECOLOGIA, DOCUMENTACION Y ARCHIVO",
      value: "102",
    },
  },
  {
    label: "LICENCIADO EN BIOFARMACEUTICA",
    value: {
      CodigoSierp: "162",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN BIOPHARMACEUTICS",
      label: "LICENCIADO EN BIOFARMACEUTICA",
      value: "103",
    },
  },
  {
    label: "LICENCIADO EN BIOFISICA",
    value: {
      CodigoSierp: "277",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN BIOPHYSICS",
      label: "LICENCIADO EN BIOFISICA",
      value: "104",
    },
  },
  {
    label: "LICENCIADO EN BOTANICA",
    value: {
      CodigoSierp: "278",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN BOTANY",
      label: "LICENCIADO EN BOTANICA",
      value: "105",
    },
  },
  {
    label: "LICENCIADO EN CIENCIAS DE LA EDUCACION",
    value: {
      CodigoSierp: "159",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN EDUCATION",
      label: "LICENCIADO EN CIENCIAS DE LA EDUCACION",
      value: "106",
    },
  },
  {
    label: "LICENCIADO EN CIENCIAS DE LA EDUCACION BASICA",
    value: {
      CodigoSierp: "279",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN BASIC EDUCATION SCIENCES",
      label: "LICENCIADO EN CIENCIAS DE LA EDUCACION BASICA",
      value: "107",
    },
  },
  {
    label: "LICENCIADO EN CIENCIAS DE LA EDUCACION ESPECIAL",
    value: {
      CodigoSierp: "280",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN SPECIAL EDUCATION SCIENCES",
      label: "LICENCIADO EN CIENCIAS DE LA EDUCACION ESPECIAL",
      value: "108",
    },
  },
  {
    label: "LICENCIADO EN CIENCIAS DE LA EDUCACION INICIAL",
    value: {
      CodigoSierp: "281",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN INITIAL EDUCATION SCIENCES",
      label: "LICENCIADO EN CIENCIAS DE LA EDUCACION INICIAL",
      value: "109",
    },
  },
  {
    label: "LICENCIADO EN CIENCIAS DE LA EDUCACION INTERCULTURAL BILINGUE",
    value: {
      CodigoSierp: "282",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN INTERCULTURAL BILINGUAL EDUCATION SCIENCES",
      label: "LICENCIADO EN CIENCIAS DE LA EDUCACION INTERCULTURAL BILINGUE",
      value: "110",
    },
  },
  {
    label: "LICENCIADO EN CIENCIAS MILITARES",
    value: {
      CodigoSierp: "283",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN MILITARY SCIENCES",
      label: "LICENCIADO EN CIENCIAS MILITARES",
      value: "111",
    },
  },
  {
    label: "LICENCIADO EN CIENCIAS POLICIALES",
    value: {
      CodigoSierp: "284",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN POLICE SCIENCES",
      label: "LICENCIADO EN CIENCIAS POLICIALES",
      value: "112",
    },
  },
  {
    label: "LICENCIADO EN CIENCIAS POLITICAS",
    value: {
      CodigoSierp: "285",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN POLITICAL SCIENCE",
      label: "LICENCIADO EN CIENCIAS POLITICAS",
      value: "113",
    },
  },
  {
    label: "LICENCIADO EN CINE",
    value: {
      CodigoSierp: "286",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN FILM",
      label: "LICENCIADO EN CINE",
      value: "114",
    },
  },
  {
    label: "LICENCIADO EN COMERCIO EXTERIOR",
    value: {
      CodigoSierp: "287",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN FOREIGN TRADE",
      label: "LICENCIADO EN COMERCIO EXTERIOR",
      value: "115",
    },
  },
  {
    label: "LICENCIADO EN COMUNICACION",
    value: {
      CodigoSierp: "154",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN COMMUNICATION",
      label: "LICENCIADO EN COMUNICACION",
      value: "116",
    },
  },
  {
    label: "LICENCIADO EN CONTABILIDAD Y AUDITORIA",
    value: {
      CodigoSierp: "117",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN ACCOUNTING AND AUDITING",
      label: "LICENCIADO EN CONTABILIDAD Y AUDITORIA",
      value: "117",
    },
  },
  {
    label: "LICENCIADO EN CRITICA E HISTORIA DEL ARTE",
    value: {
      CodigoSierp: "288",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN CRITICISM AND HISTORY OF ART",
      label: "LICENCIADO EN CRITICA E HISTORIA DEL ARTE",
      value: "118",
    },
  },
  {
    label: "LICENCIADO EN CURADURIA",
    value: {
      CodigoSierp: "289",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN CURATORSHIP",
      label: "LICENCIADO EN CURADURIA",
      value: "119",
    },
  },
  {
    label: "LICENCIADO EN DEMOGRAFIA",
    value: {
      CodigoSierp: "290",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN DEMOGRAPHY",
      label: "LICENCIADO EN DEMOGRAFIA",
      value: "120",
    },
  },
  {
    label: "LICENCIADO EN DEPORTE ADAPTADO",
    value: {
      CodigoSierp: "291",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN ADAPTED SPORTS",
      label: "LICENCIADO EN DEPORTE ADAPTADO",
      value: "121",
    },
  },
  {
    label: "LICENCIADO EN DESARROLLO INFANTIL INTEGRAL",
    value: {
      CodigoSierp: "292",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN COMPREHENSIVE CHILD DEVELOPMENT",
      label: "LICENCIADO EN DESARROLLO INFANTIL INTEGRAL",
      value: "122",
    },
  },
  {
    label: "LICENCIADO EN DESARROLLO LOCAL",
    value: {
      CodigoSierp: "293",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN LOCAL DEVELOPMENT",
      label: "LICENCIADO EN DESARROLLO LOCAL",
      value: "123",
    },
  },
  {
    label: "LICENCIADO EN DISEÑO DE INTERIORES",
    value: {
      CodigoSierp: "294",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN INTERIOR DESIGN",
      label: "LICENCIADO EN DISEÑO DE INTERIORES",
      value: "124",
    },
  },
  {
    label: "LICENCIADO EN DISEÑO DE PRODUCTOS",
    value: {
      CodigoSierp: "295",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PRODUCT DESIGN",
      label: "LICENCIADO EN DISEÑO DE PRODUCTOS",
      value: "125",
    },
  },
  {
    label: "LICENCIADO EN DISEÑO GRAFICO",
    value: {
      CodigoSierp: "121",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN GRAPHIC DESIGN",
      label: "LICENCIADO EN DISEÑO GRAFICO",
      value: "126",
    },
  },
  {
    label: "LICENCIADO EN DISEÑO TEXTIL E INDUMENTARIA",
    value: {
      CodigoSierp: "120",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN TEXTILE DESIGN AND CLOTHING",
      label: "LICENCIADO EN DISEÑO TEXTIL E INDUMENTARIA",
      value: "127",
    },
  },
  {
    label: "LICENCIADO EN ECOLOGIA",
    value: {
      CodigoSierp: "296",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN ECOLOGY",
      label: "LICENCIADO EN ECOLOGIA",
      value: "128",
    },
  },
  {
    label: "LICENCIADO EN ECONOMIA",
    value: {
      CodigoSierp: "297",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN ECONOMICS",
      label: "LICENCIADO EN ECONOMIA",
      value: "129",
    },
  },
  {
    label: "LICENCIADO EN ECONOMIA MATEMATICA",
    value: {
      CodigoSierp: "298",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN MATHEMATICAL ECONOMICS",
      label: "LICENCIADO EN ECONOMIA MATEMATICA",
      value: "130",
    },
  },
  {
    label: "LICENCIADO EN EMERGENCIAS MEDICAS",
    value: {
      CodigoSierp: "299",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN EMERGENCY MEDICINE",
      label: "LICENCIADO EN EMERGENCIAS MEDICAS",
      value: "131",
    },
  },
  {
    label: "LICENCIADO EN ENFERMERIA",
    value: {
      CodigoSierp: "124",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN NURSING",
      label: "LICENCIADO EN ENFERMERIA",
      value: "89",
    },
  },
  {
    label: "LICENCIADO EN ENTRENAMIENTO DEPORTIVO",
    value: {
      CodigoSierp: "300",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN SPORTS TRAINING",
      label: "LICENCIADO EN ENTRENAMIENTO DEPORTIVO",
      value: "132",
    },
  },
  {
    label: "LICENCIADO EN ESTUDIOS CULTURALES",
    value: {
      CodigoSierp: "301",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN CULTURAL STUDIES",
      label: "LICENCIADO EN ESTUDIOS CULTURALES",
      value: "133",
    },
  },
  {
    label: "LICENCIADO EN FARMACIA",
    value: {
      CodigoSierp: "302",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PHARMACY",
      label: "LICENCIADO EN FARMACIA",
      value: "134",
    },
  },
  {
    label: "LICENCIADO EN FILOSOFIA",
    value: {
      CodigoSierp: "303",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PHILOSOPHY",
      label: "LICENCIADO EN FILOSOFIA",
      value: "135",
    },
  },
  {
    label: "LICENCIADO EN FINANZAS",
    value: {
      CodigoSierp: "304",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN FINANCE",
      label: "LICENCIADO EN FINANZAS",
      value: "136",
    },
  },
  {
    label: "LICENCIADO EN FISIOTERAPIA",
    value: {
      CodigoSierp: "305",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PHYSIOTHERAPY",
      label: "LICENCIADO EN FISIOTERAPIA",
      value: "137",
    },
  },
  {
    label: "LICENCIADO EN GASTRONOMIA",
    value: {
      CodigoSierp: "306",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN GASTRONOMY",
      label: "LICENCIADO EN GASTRONOMIA",
      value: "138",
    },
  },
  {
    label: "LICENCIADO EN GENERO Y DESARROLLO",
    value: {
      CodigoSierp: "307",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN GENDER AND DEVELOPMENT",
      label: "LICENCIADO EN GENERO Y DESARROLLO",
      value: "139",
    },
  },
  {
    label: "LICENCIADO EN GEOGRAFIA Y TERRITORIO",
    value: {
      CodigoSierp: "308",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN GEOGRAPHY AND TERRITORY",
      label: "LICENCIADO EN GEOGRAFIA Y TERRITORIO",
      value: "140",
    },
  },
  {
    label: "LICENCIADO EN GERONTOLOGIA",
    value: {
      CodigoSierp: "309",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN GERONTOLOGY",
      label: "LICENCIADO EN GERONTOLOGIA",
      value: "141",
    },
  },
  {
    label: "LICENCIADO EN GESTION AMBIENTAL",
    value: {
      CodigoSierp: "310",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN ENVIRONMENTAL MANAGEMENT",
      label: "LICENCIADO EN GESTION AMBIENTAL",
      value: "142",
    },
  },
  {
    label: "LICENCIADO EN GESTION DE LA INFORMACION",
    value: {
      CodigoSierp: "311",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN INFORMATION MANAGEMENT",
      label: "LICENCIADO EN GESTION DE LA INFORMACION",
      value: "143",
    },
  },
  {
    label: "LICENCIADO EN GESTION DE RIESGOS Y DESASTRES",
    value: {
      CodigoSierp: "312",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN RISK AND DISASTER MANAGEMENT",
      label: "LICENCIADO EN GESTION DE RIESGOS Y DESASTRES",
      value: "144",
    },
  },
  {
    label: "LICENCIADO EN GESTION DEL TALENTO HUMANO",
    value: {
      CodigoSierp: "313",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN HUMAN TALENT MANAGEMENT",
      label: "LICENCIADO EN GESTION DEL TALENTO HUMANO",
      value: "145",
    },
  },
  {
    label: "LICENCIADO EN GESTION DEL TRANSPORTE",
    value: {
      CodigoSierp: "314",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN TRANSPORTATION MANAGEMENT",
      label: "LICENCIADO EN GESTION DEL TRANSPORTE",
      value: "146",
    },
  },
  {
    label: "LICENCIADO EN GESTION SOCIAL Y DESARROLLO",
    value: {
      CodigoSierp: "315",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN SOCIAL MANAGEMENT AND DEVELOPMENT",
      label: "LICENCIADO EN GESTION SOCIAL Y DESARROLLO",
      value: "147",
    },
  },
  {
    label: "LICENCIADO EN HISTORIA",
    value: {
      CodigoSierp: "316",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN HISTORY",
      label: "LICENCIADO EN HISTORIA",
      value: "148",
    },
  },
  {
    label: "LICENCIADO EN HOSPITALIDAD Y HOTELERIA",
    value: {
      CodigoSierp: "317",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN HOSPITALITY AND HOTEL MANAGEMENT",
      label: "LICENCIADO EN HOSPITALIDAD Y HOTELERIA",
      value: "149",
    },
  },
  {
    label: "LICENCIADO EN IDIOMA (CASTELLANO-INGLES- FRANCES, ETC)",
    value: {
      CodigoSierp: "265",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LANGUAGE GRADUATE (SPANISH-ENGLISH-FRENCH, ETC.)",
      label: "LICENCIADO EN IDIOMA (CASTELLANO-INGLES- FRANCES, ETC)",
      value: "87",
    },
  },
  {
    label: "LICENCIADO EN IMAGENOLOGIA Y RADIODIAGNOSTICO",
    value: {
      CodigoSierp: "318",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN RADIOLOGY AND RADIO DIAGNOSTICS",
      label: "LICENCIADO EN IMAGENOLOGIA Y RADIODIAGNOSTICO",
      value: "150",
    },
  },
  {
    label: "LICENCIADO EN LABORATORIO CLINICO",
    value: {
      CodigoSierp: "319",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN CLINICAL LABORATORY",
      label: "LICENCIADO EN LABORATORIO CLINICO",
      value: "151",
    },
  },
  {
    label: "LICENCIADO EN LINGUISTICA",
    value: {
      CodigoSierp: "320",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN LINGUISTICS",
      label: "LICENCIADO EN LINGUISTICA",
      value: "152",
    },
  },
  {
    label: "LICENCIADO EN LITERATURA",
    value: {
      CodigoSierp: "321",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN LITERATURE",
      label: "LICENCIADO EN LITERATURA",
      value: "153",
    },
  },
  {
    label: "LICENCIADO EN LOGOPEDIA",
    value: {
      CodigoSierp: "125",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN LOGOPEDICS",
      label: "LICENCIADO EN LOGOPEDIA",
      value: "154",
    },
  },
  {
    label: "LICENCIADO EN MERCADOTECNIA",
    value: {
      CodigoSierp: "322",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN MARKETING",
      label: "LICENCIADO EN MERCADOTECNIA",
      value: "155",
    },
  },
  {
    label: "LICENCIADO EN MICROBIOLOGIA",
    value: {
      CodigoSierp: "323",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN MICROBIOLOGY",
      label: "LICENCIADO EN MICROBIOLOGIA",
      value: "156",
    },
  },
  {
    label: "LICENCIADO EN NEUROCIENCIAS",
    value: {
      CodigoSierp: "324",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN NEUROSCIENCES",
      label: "LICENCIADO EN NEUROCIENCIAS",
      value: "157",
    },
  },
  {
    label: "LICENCIADO EN NUTRICION Y DIETETICA",
    value: {
      CodigoSierp: "152",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN NUTRITION AND DIETETICS",
      label: "LICENCIADO EN NUTRICION Y DIETETICA",
      value: "158",
    },
  },
  {
    label: "LICENCIADO EN OBSTETRICIA",
    value: {
      CodigoSierp: "146",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN OBSTETRICS",
      label: "LICENCIADO EN OBSTETRICIA",
      value: "159",
    },
  },
  {
    label: "LICENCIADO EN OPTOMETRIA",
    value: {
      CodigoSierp: "325",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN OPTOMETRY",
      label: "LICENCIADO EN OPTOMETRIA",
      value: "160",
    },
  },
  {
    label: "LICENCIADO EN ORIENTACION FAMILIAR",
    value: {
      CodigoSierp: "326",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN FAMILY GUIDANCE",
      label: "LICENCIADO EN ORIENTACION FAMILIAR",
      value: "161",
    },
  },
  {
    label: "LICENCIADO EN PEDAGOGIA DE LA FILOSOFIA",
    value: {
      CodigoSierp: "327",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PHILOSOPHY EDUCATION",
      label: "LICENCIADO EN PEDAGOGIA DE LA FILOSOFIA",
      value: "162",
    },
  },
  {
    label: "LICENCIADO EN PEDAGOGIA DE LA HISTORIA Y LAS CIENCIAS SOCIALES",
    value: {
      CodigoSierp: "328",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN HISTORY AND SOCIAL SCIENCES EDUCATION",
      label: "LICENCIADO EN PEDAGOGIA DE LA HISTORIA Y LAS CIENCIAS SOCIALES",
      value: "163",
    },
  },
  {
    label: "LICENCIADO EN PEDAGOGIA DE LA INFORMATICA",
    value: {
      CodigoSierp: "329",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN COMPUTER SCIENCE EDUCATION",
      label: "LICENCIADO EN PEDAGOGIA DE LA INFORMATICA",
      value: "164",
    },
  },
  {
    label: "LICENCIADO EN PEDAGOGIA DE LA LENGUA Y LITERATURA",
    value: {
      CodigoSierp: "330",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN LANGUAGE AND LITERATURE EDUCATION",
      label: "LICENCIADO EN PEDAGOGIA DE LA LENGUA Y LITERATURA",
      value: "165",
    },
  },
  {
    label: "LICENCIADO EN PEDAGOGIA DE LA QUIMICA Y BIOLOGIA",
    value: {
      CodigoSierp: "331",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN CHEMISTRY AND BIOLOGY EDUCATION",
      label: "LICENCIADO EN PEDAGOGIA DE LA QUIMICA Y BIOLOGIA",
      value: "166",
    },
  },
  {
    label: "LICENCIADO EN PEDAGOGIA DE LA RELIGION",
    value: {
      CodigoSierp: "332",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN RELIGIOUS EDUCATION",
      label: "LICENCIADO EN PEDAGOGIA DE LA RELIGION",
      value: "167",
    },
  },
  {
    label: "LICENCIADO EN PEDAGOGIA DE LAS ARTES",
    value: {
      CodigoSierp: "333",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN ARTS EDUCATION",
      label: "LICENCIADO EN PEDAGOGIA DE LAS ARTES",
      value: "168",
    },
  },
  {
    label: "LICENCIADO EN PEDAGOGIA DE LAS MATEMATICAS Y LA FISICA",
    value: {
      CodigoSierp: "334",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN MATHEMATICS AND PHYSICS EDUCATION",
      label: "LICENCIADO EN PEDAGOGIA DE LAS MATEMATICAS Y LA FISICA",
      value: "169",
    },
  },
  {
    label: "LICENCIADO EN PEDAGOGIA DEL IDIOMA",
    value: {
      CodigoSierp: "335",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN LANGUAGE EDUCATION",
      label: "LICENCIADO EN PEDAGOGIA DEL IDIOMA",
      value: "170",
    },
  },
  {
    label: "LICENCIADO EN PERIODISMO",
    value: {
      CodigoSierp: "336",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN JOURNALISM",
      label: "LICENCIADO EN PERIODISMO",
      value: "171",
    },
  },
  {
    label: "LICENCIADO EN PRODUCCION MUSICAL Y SONIDO",
    value: {
      CodigoSierp: "337",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN MUSICAL PRODUCTION AND SOUND",
      label: "LICENCIADO EN PRODUCCION MUSICAL Y SONIDO",
      value: "172",
    },
  },
  {
    label: "LICENCIADO EN PRODUCCION PARA MEDIOS DE COMUNICACION",
    value: {
      CodigoSierp: "114",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PRODUCTION FOR AUDIOVISUAL MEDIA",
      label: "LICENCIADO EN PRODUCCION PARA MEDIOS DE COMUNICACION",
      value: "173",
    },
  },
  {
    label: "LICENCIADO EN PROMOCION DE SALUD",
    value: {
      CodigoSierp: "338",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN HEALTH PROMOTION",
      label: "LICENCIADO EN PROMOCION DE SALUD",
      value: "174",
    },
  },
  {
    label: "LICENCIADO EN PSICOLOGIA",
    value: {
      CodigoSierp: "160",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PSYCHOLOGY",
      label: "LICENCIADO EN PSICOLOGIA",
      value: "175",
    },
  },
  {
    label: "LICENCIADO EN PSICOPEDAGOGIA",
    value: {
      CodigoSierp: "123",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PSYCHOPEDAGOGY",
      label: "LICENCIADO EN PSICOPEDAGOGIA",
      value: "176",
    },
  },
  {
    label: "LICENCIADO EN PUBLICIDAD",
    value: {
      CodigoSierp: "161",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN ADVERTISING",
      label: "LICENCIADO EN PUBLICIDAD",
      value: "177",
    },
  },
  {
    label: "LICENCIADO EN RELACIONES INTERNACIONALES",
    value: {
      CodigoSierp: "339",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN INTERNATIONAL RELATIONS",
      label: "LICENCIADO EN RELACIONES INTERNACIONALES",
      value: "178",
    },
  },
  {
    label: "LICENCIADO EN SALUD PUBLICA",
    value: {
      CodigoSierp: "340",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN PUBLIC HEALTH",
      label: "LICENCIADO EN SALUD PUBLICA",
      value: "179",
    },
  },
  {
    label: "LICENCIADO EN SALUD Y SEGURIDAD OCUPACIONAL",
    value: {
      CodigoSierp: "341",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRADUATE IN OCCUPATIONAL HEALTH AND SAFETY",
      label: "LICENCIADO EN SALUD Y SEGURIDAD OCUPACIONAL",
      value: "180",
    },
  },
  {
    label: "LICENCIADO EN SEGURIDAD CIUDADANA",
    value: {
      CodigoSierp: "342",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BACHELOR OF CITIZEN SECURITY",
      label: "LICENCIADO EN SEGURIDAD CIUDADANA",
      value: "181",
    },
  },
  {
    label: "LICENCIADO EN SOCIOLOGIA",
    value: {
      CodigoSierp: "343",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BACHELOR OF SOCIOLOGY",
      label: "LICENCIADO EN SOCIOLOGIA",
      value: "182",
    },
  },
  {
    label: "LICENCIADO EN TECNICAS AUDIOVISUALES",
    value: {
      CodigoSierp: "344",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BACHELOR OF AUDIOVISUAL TECHNIQUES",
      label: "LICENCIADO EN TECNICAS AUDIOVISUALES",
      value: "183",
    },
  },
  {
    label: "LICENCIADO EN TEOLOGIA",
    value: {
      CodigoSierp: "345",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BACHELOR OF THEOLOGY",
      label: "LICENCIADO EN TEOLOGIA",
      value: "184",
    },
  },
  {
    label: "LICENCIADO EN TERAPIA OCUPACIONAL",
    value: {
      CodigoSierp: "346",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BACHELOR OF OCCUPATIONAL THERAPY",
      label: "LICENCIADO EN TERAPIA OCUPACIONAL",
      value: "185",
    },
  },
  {
    label: "LICENCIADO EN TERAPIAS ALTERNATIVAS",
    value: {
      CodigoSierp: "347",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BACHELOR OF ALTERNATIVE THERAPIES",
      label: "LICENCIADO EN TERAPIAS ALTERNATIVAS",
      value: "186",
    },
  },
  {
    label: "LICENCIADO EN TRABAJO SOCIAL",
    value: {
      CodigoSierp: "348",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BACHELOR OF SOCIAL WORK",
      label: "LICENCIADO EN TRABAJO SOCIAL",
      value: "187",
    },
  },
  {
    label: "LICENCIADO EN TURISMO",
    value: {
      CodigoSierp: "349",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BACHELOR OF TOURISM",
      label: "LICENCIADO EN TURISMO",
      value: "188",
    },
  },
  {
    label: "LICENCIADO EN ZOOLOGIA",
    value: {
      CodigoSierp: "350",
      CodigoSos: null,
      CodigoVt: null,
      Value: "BACHELOR OF ZOOLOGY",
      label: "LICENCIADO EN ZOOLOGIA",
      value: "189",
    },
  },
  {
    label: "MATEMATICO",
    value: {
      CodigoSierp: "351",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MATHEMATICIAN",
      label: "MATEMATICO",
      value: "190",
    },
  },
  {
    label: "MEDICO",
    value: {
      CodigoSierp: "148",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DOCTOR",
      label: "MEDICO",
      value: "191",
    },
  },
  {
    label: "MEDICO VETERINARIO",
    value: {
      CodigoSierp: "149",
      CodigoSos: null,
      CodigoVt: null,
      Value: "VETERINARIAN DOCTOR",
      label: "MEDICO VETERINARIO",
      value: "192",
    },
  },
  {
    label: "MILITAR",
    value: {
      CodigoSierp: "150",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MILITARY",
      label: "MILITAR",
      value: "193",
    },
  },
  {
    label: "NO TIENE TITULO PROFESIONAL",
    value: {
      CodigoSierp: null,
      CodigoSos: null,
      CodigoVt: null,
      Value: "NO PROFESSIONAL TITLE",
      label: "NO TIENE TITULO PROFESIONAL",
      value: "321",
    },
  },
  {
    label: "ODONTOLOGO",
    value: {
      CodigoSierp: "153",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DENTIST",
      label: "ODONTOLOGO",
      value: "194",
    },
  },
  {
    label: "OFICIAL DE POLICIA",
    value: {
      CodigoSierp: "158",
      CodigoSos: null,
      CodigoVt: null,
      Value: "POLICE OFFICER",
      label: "OFICIAL DE POLICIA",
      value: "195",
    },
  },
  {
    label: "PETROQUIMICO",
    value: {
      CodigoSierp: "352",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PETROCHEMIST",
      label: "PETROQUIMICO",
      value: "196",
    },
  },
  {
    label: "PILOTO COMERCIAL",
    value: {
      CodigoSierp: "156",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COMMERCIAL PILOT",
      label: "PILOTO COMERCIAL",
      value: "197",
    },
  },
  {
    label: "PILOTO DE AVIACION",
    value: {
      CodigoSierp: "155",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AVIATION PILOT",
      label: "PILOTO DE AVIACION",
      value: "198",
    },
  },
  {
    label: "PRODUCTOR DE MEDIOS IMPRESOS CON NIVEL EQUIVALENTE A TECNOLOGO",
    value: {
      CodigoSierp: "353",
      CodigoSos: null,
      CodigoVt: null,
      Value:
        "PRODUCER OF PRINTED MEDIA WITH EQUIVALENT LEVEL TO TECHNOLOGIST",
      label: "PRODUCTOR DE MEDIOS IMPRESOS CON NIVEL EQUIVALENTE A TECNOLOGO",
      value: "199",
    },
  },
  {
    label: "PRODUCTOR EN COMUNICACION AUDIOVISUAL CON NIVEL EQUIVALENTE A",
    value: {
      CodigoSierp: "354",
      CodigoSos: null,
      CodigoVt: null,
      Value:
        "PRODUCER IN AUDIOVISUAL COMMUNICATION WITH EQUIVALENT LEVEL TO TECHNOLOGIST",
      label: "PRODUCTOR EN COMUNICACION AUDIOVISUAL CON NIVEL EQUIVALENTE A",
      value: "200",
    },
  },
  {
    label:
      "PRODUCTOR EN TELEVISION COMUNITARIA CON NIVEL EQUIVALENTE A TECNOLOGO",
    value: {
      CodigoSierp: "355",
      CodigoSos: null,
      CodigoVt: null,
      Value:
        "PRODUCER IN COMMUNITY TELEVISION WITH EQUIVALENT LEVEL TO TECHNOLOGIST",
      label:
        "PRODUCTOR EN TELEVISION COMUNITARIA CON NIVEL EQUIVALENTE A TECNOLOGO",
      value: "201",
    },
  },
  {
    label: "PRODUCTOR Y CONDUCTOR DE RADIO CON NIVEL EQUIVALENTE A TECNOLOGO",
    value: {
      CodigoSierp: "356",
      CodigoSos: null,
      CodigoVt: null,
      Value: "RADIO PRODUCER AND HOST WITH EQUIVALENT LEVEL TO TECHNOLOGIST",
      label:
        "PRODUCTOR Y CONDUCTOR DE RADIO CON NIVEL EQUIVALENTE A TECNOLOGO",
      value: "202",
    },
  },
  {
    label: "QUIMICO",
    value: {
      CodigoSierp: "357",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CHEMIST",
      label: "QUIMICO",
      value: "203",
    },
  },
  {
    label: "RESTAURADOR Y CONSERVADOR DE BIENES CULTURALES",
    value: {
      CodigoSierp: "358",
      CodigoSos: null,
      CodigoVt: null,
      Value: "RESTORER AND CONSERVATOR OF CULTURAL HERITAGE",
      label: "RESTAURADOR Y CONSERVADOR DE BIENES CULTURALES",
      value: "204",
    },
  },
  {
    label: "SIN INFORMACION",
    value: {
      CodigoSierp: "172",
      CodigoSos: null,
      CodigoVt: null,
      Value: "NO INFORMATION",
      label: "SIN INFORMACION",
      value: "322",
    },
  },
  {
    label: "TECNICO AGROPECUARIO",
    value: {
      CodigoSierp: "359",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AGRICULTURAL TECHNICIAN",
      label: "TECNICO AGROPECUARIO",
      value: "205",
    },
  },
  {
    label: "TECNICO AUXILIAR EN ENFERMERIA",
    value: {
      CodigoSierp: "111",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AUXILIARY NURSE",
      label: "TECNICO AUXILIAR EN ENFERMERIA",
      value: "206",
    },
  },
  {
    label: "TECNICO DE BIBLIOTECAS, DOCUMENTACION Y ARCHIVO",
    value: {
      CodigoSierp: "360",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LIBRARY, DOCUMENTATION, AND ARCHIVE TECHNICIAN",
      label: "TECNICO DE BIBLIOTECAS, DOCUMENTACION Y ARCHIVO",
      value: "207",
    },
  },
  {
    label: "TECNICO DE MUSEOS",
    value: {
      CodigoSierp: "361",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MUSEUM TECHNICIAN",
      label: "TECNICO DE MUSEOS",
      value: "208",
    },
  },
  {
    label: "TECNICO EN ACUICULTURA",
    value: {
      CodigoSierp: "362",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AQUACULTURE TECHNICIAN",
      label: "TECNICO EN ACUICULTURA",
      value: "209",
    },
  },
  {
    label: "TECNICO EN ADMNINISTRACION",
    value: {
      CodigoSierp: "363",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ADMINISTRATION TECHNICIAN",
      label: "TECNICO EN ADMNINISTRACION",
      value: "210",
    },
  },
  {
    label: "TECNICO EN ALIMENTOS Y BEBIDAS",
    value: {
      CodigoSierp: "364",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FOOD AND BEVERAGE TECHNICIAN",
      label: "TECNICO EN ALIMENTOS Y BEBIDAS",
      value: "211",
    },
  },
  {
    label: "TECNICO EN ANIMACION DIGITAL",
    value: {
      CodigoSierp: "365",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DIGITAL ANIMATION TECHNICIAN",
      label: "TECNICO EN ANIMACION DIGITAL",
      value: "212",
    },
  },
  {
    label: "TECNICO EN ANTROPOLOGIA",
    value: {
      CodigoSierp: "366",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ANTHROPOLOGY TECHNICIAN",
      label: "TECNICO EN ANTROPOLOGIA",
      value: "213",
    },
  },
  {
    label: "TECNICO EN ARTES",
    value: {
      CodigoSierp: "367",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ART TECHNICIAN",
      label: "TECNICO EN ARTES",
      value: "214",
    },
  },
  {
    label: "TECNICO EN ASISTENCIA SOCIAL",
    value: {
      CodigoSierp: "368",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOCIAL ASSISTANCE TECHNICIAN",
      label: "TECNICO EN ASISTENCIA SOCIAL",
      value: "215",
    },
  },
  {
    label: "TECNICO EN CALZADO",
    value: {
      CodigoSierp: "369",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FOOTWEAR TECHNICIAN",
      label: "TECNICO EN CALZADO",
      value: "216",
    },
  },
  {
    label: "TECNICO EN CARTOGRAFIA",
    value: {
      CodigoSierp: "370",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CARTOGRAPHY TECHNICIAN",
      label: "TECNICO EN CARTOGRAFIA",
      value: "217",
    },
  },
  {
    label: "TECNICO EN CIENCIAS POLITICAS",
    value: {
      CodigoSierp: "371",
      CodigoSos: null,
      CodigoVt: null,
      Value: "POLITICAL SCIENCE TECHNICIAN",
      label: "TECNICO EN CIENCIAS POLITICAS",
      value: "218",
    },
  },
  {
    label: "TECNICO EN CIENCIAS SOCIALES",
    value: {
      CodigoSierp: "372",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOCIAL SCIENCES TECHNICIAN",
      label: "TECNICO EN CIENCIAS SOCIALES",
      value: "219",
    },
  },
  {
    label: "TECNICO EN COMERCIO EXTERIOR",
    value: {
      CodigoSierp: "373",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FOREIGN TRADE TECHNICIAN",
      label: "TECNICO EN COMERCIO EXTERIOR",
      value: "220",
    },
  },
  {
    label: "TECNICO EN COMUNICACION",
    value: {
      CodigoSierp: "374",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COMMUNICATION TECHNICIAN",
      label: "TECNICO EN COMUNICACION",
      value: "221",
    },
  },
  {
    label: "TECNICO EN CONFECCION (PRENDAS DE VESTIR)",
    value: {
      CodigoSierp: "375",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MANUFACTURING TECHNICIAN (CLOTHING)",
      label: "TECNICO EN CONFECCION (PRENDAS DE VESTIR)",
      value: "222",
    },
  },
  {
    label: "TECNICO EN CONTABILIDAD Y AUDITORIA",
    value: {
      CodigoSierp: "118",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ACCOUNTING AND AUDITING TECHNICIAN",
      label: "TECNICO EN CONTABILIDAD Y AUDITORIA",
      value: "223",
    },
  },
  {
    label: "TECNICO EN DEMOGRAFIA",
    value: {
      CodigoSierp: "376",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DEMOGRAPHIC TECHNICIAN",
      label: "TECNICO EN DEMOGRAFIA",
      value: "224",
    },
  },
  {
    label: "TECNICO EN DIBUJO",
    value: {
      CodigoSierp: "377",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DRAWING TECHNICIAN",
      label: "TECNICO EN DIBUJO",
      value: "225",
    },
  },
  {
    label: "TECNICO EN DISEÑO DE INTERIORES",
    value: {
      CodigoSierp: "378",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INTERIOR DESIGN TECHNICIAN",
      label: "TECNICO EN DISEÑO DE INTERIORES",
      value: "226",
    },
  },
  {
    label: "TECNICO EN DISEÑO GRAFICO",
    value: {
      CodigoSierp: "379",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRAPHIC DESIGN TECHNICIAN",
      label: "TECNICO EN DISEÑO GRAFICO",
      value: "227",
    },
  },
  {
    label: "TECNICO EN DISEÑO TEXTIL E INDUMENTARIA",
    value: {
      CodigoSierp: "380",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TEXTILE AND CLOTHING DESIGN TECHNICIAN",
      label: "TECNICO EN DISEÑO TEXTIL E INDUMENTARIA",
      value: "228",
    },
  },
  {
    label: "TECNICO EN ECONOMIA",
    value: {
      CodigoSierp: "381",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ECONOMICS TECHNICIAN",
      label: "TECNICO EN ECONOMIA",
      value: "229",
    },
  },
  {
    label: "TECNICO EN EDUCACION",
    value: {
      CodigoSierp: "166",
      CodigoSos: null,
      CodigoVt: null,
      Value: "EDUCATION TECHNICIAN",
      label: "TECNICO EN EDUCACION",
      value: "230",
    },
  },
  {
    label: "TECNICO EN EDUCACION ESPECIAL",
    value: {
      CodigoSierp: "382",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SPECIAL EDUCATION TECHNICIAN",
      label: "TECNICO EN EDUCACION ESPECIAL",
      value: "231",
    },
  },
  {
    label: "TECNICO EN EDUCACION PARVULARIA INFANTIL Y PREPRIMARIA",
    value: {
      CodigoSierp: "383",
      CodigoSos: null,
      CodigoVt: null,
      Value: "EARLY CHILDHOOD AND PREPRIMARY EDUCATION TECHNICIAN",
      label: "TECNICO EN EDUCACION PARVULARIA INFANTIL Y PREPRIMARIA",
      value: "232",
    },
  },
  {
    label: "TECNICO EN ELECTRONICA",
    value: {
      CodigoSierp: "132",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ELECTRONICS TECHNICIAN",
      label: "TECNICO EN ELECTRONICA",
      value: "233",
    },
  },
  {
    label: "TECNICO EN ESTADISTICA",
    value: {
      CodigoSierp: "384",
      CodigoSos: null,
      CodigoVt: null,
      Value: "STATISTICS TECHNICIAN",
      label: "TECNICO EN ESTADISTICA",
      value: "234",
    },
  },
  {
    label: "TECNICO EN FARMACIA",
    value: {
      CodigoSierp: "385",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PHARMACY TECHNICIAN",
      label: "TECNICO EN FARMACIA",
      value: "235",
    },
  },
  {
    label: "TECNICO EN FINANZAS",
    value: {
      CodigoSierp: "386",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FINANCE TECHNICIAN",
      label: "TECNICO EN FINANZAS",
      value: "236",
    },
  },
  {
    label: "TECNICO EN FISICA",
    value: {
      CodigoSierp: "387",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PHYSICS TECHNICIAN",
      label: "TECNICO EN FISICA",
      value: "237",
    },
  },
  {
    label: "TECNICO EN FLORICULTURA",
    value: {
      CodigoSierp: "388",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FLORICULTURE TECHNICIAN",
      label: "TECNICO EN FLORICULTURA",
      value: "238",
    },
  },
  {
    label: "TECNICO EN FOTOGRAFIA",
    value: {
      CodigoSierp: "389",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PHOTOGRAPHY TECHNICIAN",
      label: "TECNICO EN FOTOGRAFIA",
      value: "239",
    },
  },
  {
    label: "TECNICO EN GASTRONOMIA",
    value: {
      CodigoSierp: "390",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GASTRONOMY TECHNICIAN",
      label: "TECNICO EN GASTRONOMIA",
      value: "240",
    },
  },
  {
    label: "TECNICO EN GRABACION Y PRODUCCION MUSICAL",
    value: {
      CodigoSierp: "391",
      CodigoSos: null,
      CodigoVt: null,
      Value: "RECORDING AND MUSIC PRODUCTION TECHNICIAN",
      label: "TECNICO EN GRABACION Y PRODUCCION MUSICAL",
      value: "241",
    },
  },
  {
    label: "TECNICO EN HOTELERIA",
    value: {
      CodigoSierp: "392",
      CodigoSos: null,
      CodigoVt: null,
      Value: "HOTEL MANAGEMENT TECHNICIAN",
      label: "TECNICO EN HOTELERIA",
      value: "242",
    },
  },
  {
    label: "TECNICO EN IDIOMAS",
    value: {
      CodigoSierp: "393",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LANGUAGE TECHNICIAN",
      label: "TECNICO EN IDIOMAS",
      value: "243",
    },
  },
  {
    label: "TECNICO EN LENGUAJE Y LITERATURA",
    value: {
      CodigoSierp: "394",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LANGUAGE AND LITERATURE TECHNICIAN",
      label: "TECNICO EN LENGUAJE Y LITERATURA",
      value: "244",
    },
  },
  {
    label: "TECNICO EN LOGOPEDIA",
    value: {
      CodigoSierp: "395",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LOGOPEDICS TECHNICIAN",
      label: "TECNICO EN LOGOPEDIA",
      value: "245",
    },
  },
  {
    label: "TECNICO EN MATEMATICAS",
    value: {
      CodigoSierp: "396",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MATHEMATICS TECHNICIAN",
      label: "TECNICO EN MATEMATICAS",
      value: "246",
    },
  },
  {
    label: "TECNICO EN MEDIOS AUDIOVISUALES",
    value: {
      CodigoSierp: "397",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AUDIOVISUAL MEDIA TECHNICIAN",
      label: "TECNICO EN MEDIOS AUDIOVISUALES",
      value: "247",
    },
  },
  {
    label: "TECNICO EN MERCADOTECNIA",
    value: {
      CodigoSierp: "398",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MARKETING TECHNICIAN",
      label: "TECNICO EN MERCADOTECNIA",
      value: "248",
    },
  },
  {
    label: "TECNICO EN MINERIA E INDUSTRIAS EXTRACTIVAS",
    value: {
      CodigoSierp: "399",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MINING AND EXTRACTIVE INDUSTRIES TECHNICIAN",
      label: "TECNICO EN MINERIA E INDUSTRIAS EXTRACTIVAS",
      value: "249",
    },
  },
  {
    label: "TECNICO EN MUSICA",
    value: {
      CodigoSierp: "400",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MUSIC TECHNICIAN",
      label: "TECNICO EN MUSICA",
      value: "250",
    },
  },
  {
    label: "TECNICO EN OPTOMETRIA",
    value: {
      CodigoSierp: "401",
      CodigoSos: null,
      CodigoVt: null,
      Value: "OPTOMETRY TECHNICIAN",
      label: "TECNICO EN OPTOMETRIA",
      value: "251",
    },
  },
  {
    label: "TECNICO EN PINTURA Y ESCULTURA",
    value: {
      CodigoSierp: "402",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PAINTING AND SCULPTURE TECHNICIAN",
      label: "TECNICO EN PINTURA Y ESCULTURA",
      value: "252",
    },
  },
  {
    label: "TECNICO EN PUBLICIDAD",
    value: {
      CodigoSierp: "403",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ADVERTISING TECHNICIAN",
      label: "TECNICO EN PUBLICIDAD",
      value: "253",
    },
  },
  {
    label: "TECNICO EN RELACIONES PUBLICAS",
    value: {
      CodigoSierp: "404",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PUBLIC RELATIONS TECHNICIAN",
      label: "TECNICO EN RELACIONES PUBLICAS",
      value: "254",
    },
  },
  {
    label: "TECNICO EN SEGURIDAD INDUSTRIAL",
    value: {
      CodigoSierp: "405",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INDUSTRIAL SAFETY TECHNICIAN",
      label: "TECNICO EN SEGURIDAD INDUSTRIAL",
      value: "255",
    },
  },
  {
    label: "TECNICO EN SISTEMAS",
    value: {
      CodigoSierp: "406",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SYSTEMS TECHNICIAN",
      label: "TECNICO EN SISTEMAS",
      value: "256",
    },
  },
  {
    label: "TECNICO EN SOCIOLOGIA",
    value: {
      CodigoSierp: "407",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOCIOLOGY TECHNICIAN",
      label: "TECNICO EN SOCIOLOGIA",
      value: "257",
    },
  },
  {
    label: "TECNICO EN TELECOMUNICACIONES",
    value: {
      CodigoSierp: "408",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TELECOMMUNICATIONS TECHNICIAN",
      label: "TECNICO EN TELECOMUNICACIONES",
      value: "258",
    },
  },
  {
    label: "TECNICO EN TEOLOGIA",
    value: {
      CodigoSierp: "409",
      CodigoSos: null,
      CodigoVt: null,
      Value: "THEOLOGY TECHNICIAN",
      label: "TECNICO EN TEOLOGIA",
      value: "259",
    },
  },
  {
    label: "TECNICO EN TERAPIAS ALTERATIVAS",
    value: {
      CodigoSierp: "410",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ALTERNATIVE THERAPIES TECHNICIAN",
      label: "TECNICO EN TERAPIAS ALTERATIVAS",
      value: "260",
    },
  },
  {
    label: "TECNICO EN TOPOGRAFIA",
    value: {
      CodigoSierp: "411",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TOPOGRAPHY TECHNICIAN",
      label: "TECNICO EN TOPOGRAFIA",
      value: "261",
    },
  },
  {
    label: "TECNICO FORESTAL",
    value: {
      CodigoSierp: "165",
      CodigoSos: null,
      CodigoVt: null,
      Value: "FORESTRY TECHNICIAN",
      label: "TECNICO FORESTAL",
      value: "262",
    },
  },
  {
    label: "TECNICO JURIDICO",
    value: {
      CodigoSierp: "412",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LEGAL TECHNICIAN",
      label: "TECNICO JURIDICO",
      value: "263",
    },
  },
  {
    label: "TECNICO PECUARIO",
    value: {
      CodigoSierp: "413",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LIVESTOCK TECHNICIAN",
      label: "TECNICO PECUARIO",
      value: "264",
    },
  },
  {
    label: "TECNICO PROGRAMADOR",
    value: {
      CodigoSierp: "414",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PROGRAMMING TECHNICIAN",
      label: "TECNICO PROGRAMADOR",
      value: "265",
    },
  },
  {
    label: "TECNICO SECRETARIADO EJECUTIVO",
    value: {
      CodigoSierp: "415",
      CodigoSos: null,
      CodigoVt: null,
      Value: "EXECUTIVE SECRETARY TECHNICIAN",
      label: "TECNICO SECRETARIADO EJECUTIVO",
      value: "266",
    },
  },
  {
    label: "TECNICO SUPERIOR EN CIENCIAS MILITARES",
    value: {
      CodigoSierp: "416",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNICIAN IN MILITARY SCIENCES",
      label: "TECNICO SUPERIOR EN CIENCIAS MILITARES",
      value: "267",
    },
  },
  {
    label: "TECNICO SUPERIOR EN INVESTIGACIONES DE POLICIA JUDICIAL",
    value: {
      CodigoSierp: "157",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNICIAN IN JUDICIAL POLICE INVESTIGATIONS",
      label: "TECNICO SUPERIOR EN INVESTIGACIONES DE POLICIA JUDICIAL",
      value: "268",
    },
  },
  {
    label: "TECNICO SUPERIOR EN MANTENIMIENTO ELECTRICO Y CONTROL INDUSTRIAL",
    value: {
      CodigoSierp: "131",
      CodigoSos: null,
      CodigoVt: null,
      Value:
        "SUPERIOR TECHNICIAN IN ELECTRICAL MAINTENANCE AND INDUSTRIAL CONTROL",
      label:
        "TECNICO SUPERIOR EN MANTENIMIENTO ELECTRICO Y CONTROL INDUSTRIAL",
      value: "269",
    },
  },
  {
    label: "TECNICO SUPERIOR EN MECANICA AUTOMOTRIZ",
    value: {
      CodigoSierp: "417",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNICIAN IN AUTOMOTIVE MECHANICS",
      label: "TECNICO SUPERIOR EN MECANICA AUTOMOTRIZ",
      value: "270",
    },
  },
  {
    label: "TECNICO SUPERIOR EN OBRAS CIVILES",
    value: {
      CodigoSierp: "116",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNICIAN IN CIVIL WORKS",
      label: "TECNICO SUPERIOR EN OBRAS CIVILES",
      value: "271",
    },
  },
  {
    label: "TECNICO ZOOTECNISTA",
    value: {
      CodigoSierp: "418",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ZOOTECHNICAL TECHNICIAN",
      label: "TECNICO ZOOTECNISTA",
      value: "272",
    },
  },
  {
    label: "TECNOLOGO AGROINDUSTRIAL",
    value: {
      CodigoSierp: "419",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AGROINDUSTRIAL TECHNOLOGIST",
      label: "TECNOLOGO AGROINDUSTRIAL",
      value: "273",
    },
  },
  {
    label: "TECNOLOGO AGROPECUARIA",
    value: {
      CodigoSierp: "420",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AGRICULTURAL TECHNOLOGIST",
      label: "TECNOLOGO AGROPECUARIA",
      value: "274",
    },
  },
  {
    label: "TECNOLOGO DE BIBLIOTECAS, DOCUMENTACION Y ARCHIVO",
    value: {
      CodigoSierp: "421",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LIBRARY, DOCUMENTATION, AND ARCHIVE TECHNOLOGIST",
      label: "TECNOLOGO DE BIBLIOTECAS, DOCUMENTACION Y ARCHIVO",
      value: "275",
    },
  },
  {
    label: "TECNOLOGO DE MUSEOS",
    value: {
      CodigoSierp: "422",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MUSEUM TECHNOLOGIST",
      label: "TECNOLOGO DE MUSEOS",
      value: "276",
    },
  },
  {
    label: "TECNOLOGO EN ANIMACION DIGITAL",
    value: {
      CodigoSierp: "423",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DIGITAL ANIMATION TECHNOLOGIST",
      label: "TECNOLOGO EN ANIMACION DIGITAL",
      value: "277",
    },
  },
  {
    label: "TECNOLOGO EN ANTROPOLOGIA",
    value: {
      CodigoSierp: "424",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ANTHROPOLOGY TECHNOLOGIST",
      label: "TECNOLOGO EN ANTROPOLOGIA",
      value: "278",
    },
  },
  {
    label: "TECNOLOGO EN ARTES",
    value: {
      CodigoSierp: "425",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ART TECHNOLOGIST",
      label: "TECNOLOGO EN ARTES",
      value: "279",
    },
  },
  {
    label: "TECNOLOGO EN ASISTENCIA Y TRABAJO SOCIAL",
    value: {
      CodigoSierp: "110",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOCIAL ASSISTANCE AND SOCIAL WORK TECHNOLOGIST",
      label: "TECNOLOGO EN ASISTENCIA Y TRABAJO SOCIAL",
      value: "280",
    },
  },
  {
    label: "TECNOLOGO EN CIENCIAS POLITICAS",
    value: {
      CodigoSierp: "426",
      CodigoSos: null,
      CodigoVt: null,
      Value: "POLITICAL SCIENCE TECHNOLOGIST",
      label: "TECNOLOGO EN CIENCIAS POLITICAS",
      value: "281",
    },
  },
  {
    label: "TECNOLOGO EN CIENCIAS SOCIALES",
    value: {
      CodigoSierp: "427",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOCIAL SCIENCES TECHNOLOGIST",
      label: "TECNOLOGO EN CIENCIAS SOCIALES",
      value: "282",
    },
  },
  {
    label: "TECNOLOGO EN COMPUTACION",
    value: {
      CodigoSierp: "163",
      CodigoSos: null,
      CodigoVt: null,
      Value: "COMPUTER TECHNOLOGIST",
      label: "TECNOLOGO EN COMPUTACION",
      value: "283",
    },
  },
  {
    label: "TECNOLOGO EN DECORACION DE INTERIORES",
    value: {
      CodigoSierp: "173",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INTERIOR DECORATION TECHNOLOGIST",
      label: "TECNOLOGO EN DECORACION DE INTERIORES",
      value: "284",
    },
  },
  {
    label: "TECNOLOGO EN DEMOGRAFIA",
    value: {
      CodigoSierp: "174",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DEMOGRAPHY TECHNOLOGIST",
      label: "TECNOLOGO EN DEMOGRAFIA",
      value: "285",
    },
  },
  {
    label: "TECNOLOGO EN DIBUJO",
    value: {
      CodigoSierp: "175",
      CodigoSos: null,
      CodigoVt: null,
      Value: "DRAWING TECHNOLOGIST",
      label: "TECNOLOGO EN DIBUJO",
      value: "286",
    },
  },
  {
    label: "TECNOLOGO EN DISEÑO DE INTERIORES",
    value: {
      CodigoSierp: "176",
      CodigoSos: null,
      CodigoVt: null,
      Value: "INTERIOR DESIGN TECHNOLOGIST",
      label: "TECNOLOGO EN DISEÑO DE INTERIORES",
      value: "287",
    },
  },
  {
    label: "TECNOLOGO EN DISEÑO GRAFICO",
    value: {
      CodigoSierp: "177",
      CodigoSos: null,
      CodigoVt: null,
      Value: "GRAPHIC DESIGN TECHNOLOGIST",
      label: "TECNOLOGO EN DISEÑO GRAFICO",
      value: "288",
    },
  },
  {
    label: "TECNOLOGO EN DISEÑO TEXTIL, INDUMENTARIA Y MODAS",
    value: {
      CodigoSierp: "178",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TEXTILE, CLOTHING, AND FASHION DESIGN TECHNOLOGIST",
      label: "TECNOLOGO EN DISEÑO TEXTIL, INDUMENTARIA Y MODAS",
      value: "289",
    },
  },
  {
    label: "TECNOLOGO EN ECONOMIA",
    value: {
      CodigoSierp: "179",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ECONOMICS TECHNOLOGIST",
      label: "TECNOLOGO EN ECONOMIA",
      value: "290",
    },
  },
  {
    label: "TECNOLOGO EN ESTADISTICA",
    value: {
      CodigoSierp: "180",
      CodigoSos: null,
      CodigoVt: null,
      Value: "STATISTICS TECHNOLOGIST",
      label: "TECNOLOGO EN ESTADISTICA",
      value: "291",
    },
  },
  {
    label: "TECNOLOGO EN FISICA",
    value: {
      CodigoSierp: "181",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PHYSICS TECHNOLOGIST",
      label: "TECNOLOGO EN FISICA",
      value: "292",
    },
  },
  {
    label: "TECNOLOGO EN FOTOGRAFIA",
    value: {
      CodigoSierp: "182",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PHOTOGRAPHY TECHNOLOGIST",
      label: "TECNOLOGO EN FOTOGRAFIA",
      value: "293",
    },
  },
  {
    label: "TECNOLOGO EN GRABACION Y PRODUCCION MUSICAL",
    value: {
      CodigoSierp: "183",
      CodigoSos: null,
      CodigoVt: null,
      Value: "RECORDING AND MUSIC PRODUCTION TECHNOLOGIST",
      label: "TECNOLOGO EN GRABACION Y PRODUCCION MUSICAL",
      value: "294",
    },
  },
  {
    label: "TECNOLOGO EN IDIOMAS",
    value: {
      CodigoSierp: "184",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LANGUAGE TECHNOLOGIST",
      label: "TECNOLOGO EN IDIOMAS",
      value: "295",
    },
  },
  {
    label: "TECNOLOGO EN LENGUAJE Y LITERATURA",
    value: {
      CodigoSierp: "185",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LANGUAGE AND LITERATURE TECHNOLOGIST",
      label: "TECNOLOGO EN LENGUAJE Y LITERATURA",
      value: "296",
    },
  },
  {
    label: "TECNOLOGO EN MATEMATICAS",
    value: {
      CodigoSierp: "186",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MATHEMATICS TECHNOLOGIST",
      label: "TECNOLOGO EN MATEMATICAS",
      value: "297",
    },
  },
  {
    label: "TECNOLOGO EN MEDIOS AUDIOVISUALES",
    value: {
      CodigoSierp: "187",
      CodigoSos: null,
      CodigoVt: null,
      Value: "AUDIOVISUAL MEDIA TECHNOLOGIST",
      label: "TECNOLOGO EN MEDIOS AUDIOVISUALES",
      value: "298",
    },
  },
  {
    label: "TECNOLOGO EN MUSICA",
    value: {
      CodigoSierp: "188",
      CodigoSos: null,
      CodigoVt: null,
      Value: "MUSIC TECHNOLOGIST",
      label: "TECNOLOGO EN MUSICA",
      value: "299",
    },
  },
  {
    label: "TECNOLOGO EN OPTOMETRIA",
    value: {
      CodigoSierp: "189",
      CodigoSos: null,
      CodigoVt: null,
      Value: "OPTOMETRY TECHNOLOGIST",
      label: "TECNOLOGO EN OPTOMETRIA",
      value: "300",
    },
  },
  {
    label: "TECNOLOGO EN PERIODISMO Y COMUNICACION",
    value: {
      CodigoSierp: "190",
      CodigoSos: null,
      CodigoVt: null,
      Value: "JOURNALISM AND COMMUNICATION TECHNOLOGIST",
      label: "TECNOLOGO EN PERIODISMO Y COMUNICACION",
      value: "301",
    },
  },
  {
    label: "TECNOLOGO EN PINTURA Y ESCULTURA",
    value: {
      CodigoSierp: "191",
      CodigoSos: null,
      CodigoVt: null,
      Value: "PAINTING AND SCULPTURE TECHNOLOGIST",
      label: "TECNOLOGO EN PINTURA Y ESCULTURA",
      value: "302",
    },
  },
  {
    label: "TECNOLOGO EN SALUD ORAL",
    value: {
      CodigoSierp: "192",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ORAL HEALTH TECHNOLOGIST",
      label: "TECNOLOGO EN SALUD ORAL",
      value: "303",
    },
  },
  {
    label: "TECNOLOGO EN SISTEMAS",
    value: {
      CodigoSierp: "193",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SYSTEMS TECHNOLOGIST",
      label: "TECNOLOGO EN SISTEMAS",
      value: "304",
    },
  },
  {
    label: "TECNOLOGO EN SOCIOLOGIA",
    value: {
      CodigoSierp: "194",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SOCIOLOGY TECHNOLOGIST",
      label: "TECNOLOGO EN SOCIOLOGIA",
      value: "305",
    },
  },
  {
    label: "TECNOLOGO EN TEOLOGIA",
    value: {
      CodigoSierp: "195",
      CodigoSos: null,
      CodigoVt: null,
      Value: "THEOLOGY TECHNOLOGIST",
      label: "TECNOLOGO EN TEOLOGIA",
      value: "306",
    },
  },
  {
    label: "TECNOLOGO EN TOPOGRAFIA",
    value: {
      CodigoSierp: "196",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TOPOGRAPHY TECHNOLOGIST",
      label: "TECNOLOGO EN TOPOGRAFIA",
      value: "307",
    },
  },
  {
    label: "TECNOLOGO JURIDICO",
    value: {
      CodigoSierp: "197",
      CodigoSos: null,
      CodigoVt: null,
      Value: "LEGAL TECHNOLOGIST",
      label: "TECNOLOGO JURIDICO",
      value: "308",
    },
  },
  {
    label: "TECNOLOGO QUIMICO",
    value: {
      CodigoSierp: "198",
      CodigoSos: null,
      CodigoVt: null,
      Value: "CHEMICAL TECHNOLOGIST",
      label: "TECNOLOGO QUIMICO",
      value: "309",
    },
  },
  {
    label: "TECNOLOGO SUPERIOR EN ADMINISTRACION",
    value: {
      CodigoSierp: "164",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNOLOGIST IN ADMINISTRATION",
      label: "TECNOLOGO SUPERIOR EN ADMINISTRACION",
      value: "310",
    },
  },
  {
    label: "TECNOLOGO SUPERIOR EN ADMINISTRACION FINANCIERA",
    value: {
      CodigoSierp: "199",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNOLOGIST IN FINANCIAL ADMINISTRATION",
      label: "TECNOLOGO SUPERIOR EN ADMINISTRACION FINANCIERA",
      value: "311",
    },
  },
  {
    label: "TECNOLOGO SUPERIOR EN ASISTENCIA ADMINISTRATIVA",
    value: {
      CodigoSierp: "200",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNOLOGIST IN ADMINISTRATIVE ASSISTANCE",
      label: "TECNOLOGO SUPERIOR EN ASISTENCIA ADMINISTRATIVA",
      value: "312",
    },
  },
  {
    label: "TECNOLOGO SUPERIOR EN CONSTRUCCION",
    value: {
      CodigoSierp: "143",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNOLOGIST IN CONSTRUCTION",
      label: "TECNOLOGO SUPERIOR EN CONSTRUCCION",
      value: "313",
    },
  },
  {
    label: "TECNOLOGO SUPERIOR EN EMERGENCIAS MEDICAS",
    value: {
      CodigoSierp: "167",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNOLOGIST IN MEDICAL EMERGENCIES",
      label: "TECNOLOGO SUPERIOR EN EMERGENCIAS MEDICAS",
      value: "314",
    },
  },
  {
    label: "TECNOLOGO SUPERIOR EN ENFERMERIA",
    value: {
      CodigoSierp: "109",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNOLOGIST IN NURSING",
      label: "TECNOLOGO SUPERIOR EN ENFERMERIA",
      value: "315",
    },
  },
  {
    label: "TECNOLOGO SUPERIOR EN INVESTIGACIONES DE POLICIA JUDICIAL",
    value: {
      CodigoSierp: "201",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNOLOGIST IN JUDICIAL POLICE INVESTIGATIONS",
      label: "TECNOLOGO SUPERIOR EN INVESTIGACIONES DE POLICIA JUDICIAL",
      value: "316",
    },
  },
  {
    label: "TECNOLOGO SUPERIOR EN MECANICA AUTOMOTRIZ",
    value: {
      CodigoSierp: "147",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNOLOGIST IN AUTOMOTIVE MECHANICS",
      label: "TECNOLOGO SUPERIOR EN MECANICA AUTOMOTRIZ",
      value: "317",
    },
  },
  {
    label: "TECNOLOGO SUPERIOR EN TURISMO",
    value: {
      CodigoSierp: "202",
      CodigoSos: null,
      CodigoVt: null,
      Value: "SUPERIOR TECHNOLOGIST IN TOURISM",
      label: "TECNOLOGO SUPERIOR EN TURISMO",
      value: "318",
    },
  },
  {
    label: "TECNOLOGO ZOOTECNISTA",
    value: {
      CodigoSierp: "203",
      CodigoSos: null,
      CodigoVt: null,
      Value: "ZOOTECHNICAL TECHNOLOGIST",
      label: "TECNOLOGO ZOOTECNISTA",
      value: "319",
    },
  },
  {
    label: "TOPOGRAFO",
    value: {
      CodigoSierp: "168",
      CodigoSos: null,
      CodigoVt: null,
      Value: "TOPOGRAPHER",
      label: "TOPOGRAFO",
      value: "320",
    },
  },
];

export {listProfesionFormsWeb}