const listCantonFormsWeb = [
  {
    label: "GUALAQUIZA",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1402",
      CodigoVT: "158",
      CodigoZOHO: null,
      label: "GUALAQUIZA",
      value: "184",
    },
  },
  {
    label: "LIMON INDANZA",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1403",
      CodigoVT: "159",
      CodigoZOHO: null,
      label: "LIMON INDANZA",
      value: "186",
    },
  },
  {
    label: "PALORA",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1404",
      CodigoVT: "160",
      CodigoZOHO: null,
      label: "PALORA",
      value: "190",
    },
  },
  {
    label: "SANTIAGO",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1405",
      CodigoVT: "161",
      CodigoZOHO: null,
      label: "SANTIAGO",
      value: "192",
    },
  },
  {
    label: "SUCUA",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1406",
      CodigoVT: "162",
      CodigoZOHO: null,
      label: "SUCUA",
      value: "193",
    },
  },
  {
    label: "HUAMBOYA",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1407",
      CodigoVT: "163",
      CodigoZOHO: null,
      label: "HUAMBOYA",
      value: "185",
    },
  },
  {
    label: "SAN JUAN BOSCO",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1408",
      CodigoVT: "164",
      CodigoZOHO: null,
      label: "SAN JUAN BOSCO",
      value: "191",
    },
  },
  {
    label: "TAISHA",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1409",
      CodigoVT: "165",
      CodigoZOHO: null,
      label: "TAISHA",
      value: "194",
    },
  },
  {
    label: "LOGROÑO",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1410",
      CodigoVT: "166",
      CodigoZOHO: null,
      label: "LOGROÑO",
      value: "187",
    },
  },
  {
    label: "PABLO SEXTO",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1411",
      CodigoVT: "167",
      CodigoZOHO: null,
      label: "PABLO SEXTO",
      value: "189",
    },
  },
  {
    label: "TIWINTZA",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1412",
      CodigoVT: "168",
      CodigoZOHO: null,
      label: "TIWINTZA",
      value: "195",
    },
  },
  {
    label: "TENA",
    value: {
      CodigoProvincia: "16",
      CodigoCatalogo: "1501",
      CodigoVT: "169",
      CodigoZOHO: null,
      label: "TENA",
      value: "200",
    },
  },
  {
    label: "ARCHIDONA",
    value: {
      CodigoProvincia: "16",
      CodigoCatalogo: "1503",
      CodigoVT: "170",
      CodigoZOHO: null,
      label: "ARCHIDONA",
      value: "196",
    },
  },
  {
    label: "EL CHACO",
    value: {
      CodigoProvincia: "16",
      CodigoCatalogo: "1504",
      CodigoVT: "171",
      CodigoZOHO: null,
      label: "EL CHACO",
      value: "198",
    },
  },
  {
    label: "QUIJOS",
    value: {
      CodigoProvincia: "16",
      CodigoCatalogo: "1507",
      CodigoVT: "172",
      CodigoZOHO: null,
      label: "QUIJOS",
      value: "199",
    },
  },
  {
    label: "CARLOS JULIO AROSEMENA TOLA",
    value: {
      CodigoProvincia: "16",
      CodigoCatalogo: "1509",
      CodigoVT: "173",
      CodigoZOHO: null,
      label: "CARLOS JULIO AROSEMENA TOLA",
      value: "197",
    },
  },
  {
    label: "FRANCISCO DE ORELLANA",
    value: {
      CodigoProvincia: "17",
      CodigoCatalogo: "2201",
      CodigoVT: "214",
      CodigoZOHO: null,
      label: "FRANCISCO DE ORELLANA",
      value: "204",
    },
  },
  {
    label: "AGUARICO",
    value: {
      CodigoProvincia: "17",
      CodigoCatalogo: "2202",
      CodigoVT: "215",
      CodigoZOHO: null,
      label: "AGUARICO",
      value: "201",
    },
  },
  {
    label: "LA JOYA DE LOS SACHAS",
    value: {
      CodigoProvincia: "17",
      CodigoCatalogo: "2203",
      CodigoVT: "216",
      CodigoZOHO: null,
      label: "LA JOYA DE LOS SACHAS",
      value: "202",
    },
  },
  {
    label: "LORETO",
    value: {
      CodigoProvincia: "17",
      CodigoCatalogo: "2204",
      CodigoVT: "217",
      CodigoZOHO: null,
      label: "LORETO",
      value: "203",
    },
  },
  {
    label: "PASTAZA",
    value: {
      CodigoProvincia: "18",
      CodigoCatalogo: "1601",
      CodigoVT: "174",
      CodigoZOHO: null,
      label: "PASTAZA",
      value: "207",
    },
  },
  {
    label: "MERA",
    value: {
      CodigoProvincia: "18",
      CodigoCatalogo: "1602",
      CodigoVT: "175",
      CodigoZOHO: null,
      label: "MERA",
      value: "206",
    },
  },
  {
    label: "SANTA CLARA",
    value: {
      CodigoProvincia: "18",
      CodigoCatalogo: "1603",
      CodigoVT: "176",
      CodigoZOHO: null,
      label: "SANTA CLARA",
      value: "208",
    },
  },
  {
    label: "ARAJUNO",
    value: {
      CodigoProvincia: "18",
      CodigoCatalogo: "1604",
      CodigoVT: "177",
      CodigoZOHO: null,
      label: "ARAJUNO",
      value: "205",
    },
  },
  {
    label: "DISTRITO METROPOLITANO DE QUITO",
    value: {
      CodigoProvincia: "19",
      CodigoCatalogo: "1701",
      CodigoVT: "178",
      CodigoZOHO: null,
      label: "DISTRITO METROPOLITANO DE QUITO",
      value: "1",
    },
  },
  {
    label: "CAYAMBE",
    value: {
      CodigoProvincia: "19",
      CodigoCatalogo: "1702",
      CodigoVT: "179",
      CodigoZOHO: null,
      label: "CAYAMBE",
      value: "2",
    },
  },
  {
    label: "MEJIA",
    value: {
      CodigoProvincia: "19",
      CodigoCatalogo: "1703",
      CodigoVT: "180",
      CodigoZOHO: null,
      label: "MEJIA",
      value: "4",
    },
  },
  {
    label: "PEDRO MONCAYO",
    value: {
      CodigoProvincia: "19",
      CodigoCatalogo: "1704",
      CodigoVT: "181",
      CodigoZOHO: null,
      label: "PEDRO MONCAYO",
      value: "5",
    },
  },
  {
    label: "RUMIÑAHUI",
    value: {
      CodigoProvincia: "19",
      CodigoCatalogo: "1705",
      CodigoVT: "182",
      CodigoZOHO: null,
      label: "RUMIÑAHUI",
      value: "3",
    },
  },
  {
    label: "SAN MIGUEL DE LOS BANCOS",
    value: {
      CodigoProvincia: "19",
      CodigoCatalogo: "1707",
      CodigoVT: "183",
      CodigoZOHO: null,
      label: "SAN MIGUEL DE LOS BANCOS",
      value: "8",
    },
  },
  {
    label: "PEDRO VICENTE MALDONADO",
    value: {
      CodigoProvincia: "19",
      CodigoCatalogo: "1708",
      CodigoVT: "184",
      CodigoZOHO: null,
      label: "PEDRO VICENTE MALDONADO",
      value: "7",
    },
  },
  {
    label: "PUERTO QUITO",
    value: {
      CodigoProvincia: "19",
      CodigoCatalogo: "1709",
      CodigoVT: "185",
      CodigoZOHO: null,
      label: "PUERTO QUITO",
      value: "6",
    },
  },
  {
    label: "SANTA ELENA",
    value: {
      CodigoProvincia: "20",
      CodigoCatalogo: "2401",
      CodigoVT: "219",
      CodigoZOHO: null,
      label: "SANTA ELENA",
      value: "177",
    },
  },
  {
    label: "LA LIBERTAD",
    value: {
      CodigoProvincia: "20",
      CodigoCatalogo: "2402",
      CodigoVT: "220",
      CodigoZOHO: null,
      label: "LA LIBERTAD",
      value: "209",
    },
  },
  {
    label: "SALINAS",
    value: {
      CodigoProvincia: "20",
      CodigoCatalogo: "2403",
      CodigoVT: "221",
      CodigoZOHO: null,
      label: "SALINAS",
      value: "176",
    },
  },
  {
    label: "LA CONCORDIA",
    value: {
      CodigoProvincia: "21",
      CodigoCatalogo: "2302",
      CodigoVT: "74",
      CodigoZOHO: null,
      label: "LA CONCORDIA",
      value: "126",
    },
  },
  {
    label: "SANTO DOMINGO",
    value: {
      CodigoProvincia: "21",
      CodigoCatalogo: "2301",
      CodigoVT: "218",
      CodigoZOHO: null,
      label: "SANTO DOMINGO",
      value: "118",
    },
  },
  {
    label: "LAGO AGRIO",
    value: {
      CodigoProvincia: "22",
      CodigoCatalogo: "2101",
      CodigoVT: "207",
      CodigoZOHO: null,
      label: "LAGO AGRIO",
      value: "213",
    },
  },
  {
    label: "GONZALO PIZARRO",
    value: {
      CodigoProvincia: "22",
      CodigoCatalogo: "2102",
      CodigoVT: "208",
      CodigoZOHO: null,
      label: "GONZALO PIZARRO",
      value: "212",
    },
  },
  {
    label: "PUTUMAYO",
    value: {
      CodigoProvincia: "22",
      CodigoCatalogo: "2103",
      CodigoVT: "209",
      CodigoZOHO: null,
      label: "PUTUMAYO",
      value: "214",
    },
  },
  {
    label: "SHUSHUFINDI",
    value: {
      CodigoProvincia: "22",
      CodigoCatalogo: "2104",
      CodigoVT: "210",
      CodigoZOHO: null,
      label: "SHUSHUFINDI",
      value: "215",
    },
  },
  {
    label: "SUCUMBIOS",
    value: {
      CodigoProvincia: "22",
      CodigoCatalogo: "2105",
      CodigoVT: "211",
      CodigoZOHO: null,
      label: "SUCUMBIOS",
      value: "216",
    },
  },
  {
    label: "CASCALES",
    value: {
      CodigoProvincia: "22",
      CodigoCatalogo: "2106",
      CodigoVT: "212",
      CodigoZOHO: null,
      label: "CASCALES",
      value: "210",
    },
  },
  {
    label: "CUYABENO",
    value: {
      CodigoProvincia: "22",
      CodigoCatalogo: "2107",
      CodigoVT: "213",
      CodigoZOHO: null,
      label: "CUYABENO",
      value: "211",
    },
  },
  {
    label: "AMBATO",
    value: {
      CodigoProvincia: "23",
      CodigoCatalogo: "1801",
      CodigoVT: "186",
      CodigoZOHO: null,
      label: "AMBATO",
      value: "54",
    },
  },
  {
    label: "BAÑOS DE AGUA SANTA",
    value: {
      CodigoProvincia: "23",
      CodigoCatalogo: "1802",
      CodigoVT: "187",
      CodigoZOHO: null,
      label: "BAÑOS DE AGUA SANTA",
      value: "55",
    },
  },
  {
    label: "CEVALLOS",
    value: {
      CodigoProvincia: "23",
      CodigoCatalogo: "1803",
      CodigoVT: "188",
      CodigoZOHO: null,
      label: "CEVALLOS",
      value: "56",
    },
  },
  {
    label: "MOCHA",
    value: {
      CodigoProvincia: "23",
      CodigoCatalogo: "1804",
      CodigoVT: "189",
      CodigoZOHO: null,
      label: "MOCHA",
      value: "57",
    },
  },
  {
    label: "PATATE",
    value: {
      CodigoProvincia: "23",
      CodigoCatalogo: "1805",
      CodigoVT: "190",
      CodigoZOHO: null,
      label: "PATATE",
      value: "58",
    },
  },
  {
    label: "QUERO",
    value: {
      CodigoProvincia: "23",
      CodigoCatalogo: "1806",
      CodigoVT: "191",
      CodigoZOHO: null,
      label: "QUERO",
      value: "59",
    },
  },
  {
    label: "TISALEO",
    value: {
      CodigoProvincia: "23",
      CodigoCatalogo: "1809",
      CodigoVT: "194",
      CodigoZOHO: null,
      label: "TISALEO",
      value: "62",
    },
  },
  {
    label: "ZAMORA",
    value: {
      CodigoProvincia: "24",
      CodigoCatalogo: "1901",
      CodigoVT: "195",
      CodigoZOHO: null,
      label: "ZAMORA",
      value: "225",
    },
  },
  {
    label: "CHINCHIPE",
    value: {
      CodigoProvincia: "24",
      CodigoCatalogo: "1902",
      CodigoVT: "196",
      CodigoZOHO: null,
      label: "CHINCHIPE",
      value: "218",
    },
  },
  {
    label: "NANGARITZA",
    value: {
      CodigoProvincia: "24",
      CodigoCatalogo: "1903",
      CodigoVT: "197",
      CodigoZOHO: null,
      label: "NANGARITZA",
      value: "220",
    },
  },
  {
    label: "YACUAMBI",
    value: {
      CodigoProvincia: "24",
      CodigoCatalogo: "1904",
      CodigoVT: "198",
      CodigoZOHO: null,
      label: "YACUAMBI",
      value: "223",
    },
  },
  {
    label: "YANTZAZA",
    value: {
      CodigoProvincia: "24",
      CodigoCatalogo: "1905",
      CodigoVT: "199",
      CodigoZOHO: null,
      label: "YANTZAZA",
      value: "322",
    },
  },
  {
    label: "EL PANGUI",
    value: {
      CodigoProvincia: "24",
      CodigoCatalogo: "1906",
      CodigoVT: "200",
      CodigoZOHO: null,
      label: "EL PANGUI",
      value: "219",
    },
  },
  {
    label: "CENTINELA DEL CONDOR",
    value: {
      CodigoProvincia: "24",
      CodigoCatalogo: "1907",
      CodigoVT: "201",
      CodigoZOHO: null,
      label: "CENTINELA DEL CONDOR",
      value: "217",
    },
  },
  {
    label: "PALANDA",
    value: {
      CodigoProvincia: "24",
      CodigoCatalogo: "1908",
      CodigoVT: "202",
      CodigoZOHO: null,
      label: "PALANDA",
      value: "221",
    },
  },
  {
    label: "PAQUISHA",
    value: {
      CodigoProvincia: "24",
      CodigoCatalogo: "1909",
      CodigoVT: "203",
      CodigoZOHO: null,
      label: "PAQUISHA",
      value: "222",
    },
  },
  {
    label: "SAN PEDRO DE PELILEO",
    value: {
      CodigoProvincia: "23",
      CodigoCatalogo: "1807",
      CodigoVT: "192",
      CodigoZOHO: null,
      label: "SAN PEDRO DE PELILEO",
      value: "60",
    },
  },
  {
    label: "SANTIAGO DE PILLARO",
    value: {
      CodigoProvincia: "23",
      CodigoCatalogo: "1808",
      CodigoVT: "193",
      CodigoZOHO: null,
      label: "SANTIAGO DE PILLARO",
      value: "61",
    },
  },
  {
    label: "GIRON",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0102",
      CodigoVT: "2",
      CodigoZOHO: null,
      label: "GIRON",
      value: "91",
    },
  },
  {
    label: "GUALACEO",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0103",
      CodigoVT: "3",
      CodigoZOHO: null,
      label: "GUALACEO",
      value: "92",
    },
  },
  {
    label: "SANTA ISABEL",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0108",
      CodigoVT: "8",
      CodigoZOHO: null,
      label: "SANTA ISABEL",
      value: "99",
    },
  },
  {
    label: "SIGSIG",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0109",
      CodigoVT: "9",
      CodigoZOHO: null,
      label: "SIGSIG",
      value: "101",
    },
  },
  {
    label: "CHORDELEG",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0111",
      CodigoVT: "11",
      CodigoZOHO: null,
      label: "CHORDELEG",
      value: "89",
    },
  },
  {
    label: "CUENCA",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0101",
      CodigoVT: "1",
      CodigoZOHO: null,
      label: "CUENCA",
      value: "87",
    },
  },
  {
    label: "NABON",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0104",
      CodigoVT: "4",
      CodigoZOHO: null,
      label: "NABON",
      value: "94",
    },
  },
  {
    label: "PAUTE",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0105",
      CodigoVT: "5",
      CodigoZOHO: null,
      label: "PAUTE",
      value: "96",
    },
  },
  {
    label: "PUCARA",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0106",
      CodigoVT: "6",
      CodigoZOHO: null,
      label: "PUCARA",
      value: "95",
    },
  },
  {
    label: "SAN FERNANDO",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0107",
      CodigoVT: "7",
      CodigoZOHO: null,
      label: "SAN FERNANDO",
      value: "98",
    },
  },
  {
    label: "OÑA",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0110",
      CodigoVT: "10",
      CodigoZOHO: null,
      label: "OÑA",
      value: "279",
    },
  },
  {
    label: "EL PAN",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0112",
      CodigoVT: "12",
      CodigoZOHO: null,
      label: "EL PAN",
      value: "90",
    },
  },
  {
    label: "GUACHAPALA",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0114",
      CodigoVT: "14",
      CodigoZOHO: null,
      label: "GUACHAPALA",
      value: "93",
    },
  },
  {
    label: "CHILLANES",
    value: {
      CodigoProvincia: "2",
      CodigoCatalogo: "0202",
      CodigoVT: "17",
      CodigoZOHO: null,
      label: "CHILLANES",
      value: "65",
    },
  },
  {
    label: "SAN MIGUEL",
    value: {
      CodigoProvincia: "2",
      CodigoCatalogo: "0205",
      CodigoVT: "20",
      CodigoZOHO: null,
      label: "SAN MIGUEL",
      value: "66",
    },
  },
  {
    label: "CALUMA",
    value: {
      CodigoProvincia: "2",
      CodigoCatalogo: "0206",
      CodigoVT: "21",
      CodigoZOHO: null,
      label: "CALUMA",
      value: "68",
    },
  },
  {
    label: "AZOGUES",
    value: {
      CodigoProvincia: "3",
      CodigoCatalogo: "0301",
      CodigoVT: "23",
      CodigoZOHO: null,
      label: "AZOGUES",
      value: "80",
    },
  },
  {
    label: "BIBLIAN",
    value: {
      CodigoProvincia: "3",
      CodigoCatalogo: "0302",
      CodigoVT: "24",
      CodigoZOHO: null,
      label: "BIBLIAN",
      value: "81",
    },
  },
  {
    label: "LA TRONCAL",
    value: {
      CodigoProvincia: "3",
      CodigoCatalogo: "0304",
      CodigoVT: "26",
      CodigoZOHO: null,
      label: "LA TRONCAL",
      value: "84",
    },
  },
  {
    label: "DELEG",
    value: {
      CodigoProvincia: "3",
      CodigoCatalogo: "0306",
      CodigoVT: "28",
      CodigoZOHO: null,
      label: "DELEG",
      value: "86",
    },
  },
  {
    label: "SUSCAL",
    value: {
      CodigoProvincia: "3",
      CodigoCatalogo: "0307",
      CodigoVT: "29",
      CodigoZOHO: null,
      label: "SUSCAL",
      value: "83",
    },
  },
  {
    label: "TULCAN",
    value: {
      CodigoProvincia: "4",
      CodigoCatalogo: "0401",
      CodigoVT: "30",
      CodigoZOHO: null,
      label: "TULCAN",
      value: "35",
    },
  },
  {
    label: "SAN PEDRO DE HUACA",
    value: {
      CodigoProvincia: "4",
      CodigoCatalogo: "0406",
      CodigoVT: "35",
      CodigoZOHO: null,
      label: "SAN PEDRO DE HUACA",
      value: "36",
    },
  },
  {
    label: "RIOBAMBA",
    value: {
      CodigoProvincia: "5",
      CodigoCatalogo: "0601",
      CodigoVT: "43",
      CodigoZOHO: null,
      label: "RIOBAMBA",
      value: "70",
    },
  },
  {
    label: "ALAUSI",
    value: {
      CodigoProvincia: "5",
      CodigoCatalogo: "0602",
      CodigoVT: "44",
      CodigoZOHO: null,
      label: "ALAUSI",
      value: "71",
    },
  },
  {
    label: "GUAMOTE",
    value: {
      CodigoProvincia: "5",
      CodigoCatalogo: "0606",
      CodigoVT: "48",
      CodigoZOHO: null,
      label: "GUAMOTE",
      value: "76",
    },
  },
  {
    label: "GUANO",
    value: {
      CodigoProvincia: "5",
      CodigoCatalogo: "0607",
      CodigoVT: "49",
      CodigoZOHO: null,
      label: "GUANO",
      value: "77",
    },
  },
  {
    label: "PENIPE",
    value: {
      CodigoProvincia: "5",
      CodigoCatalogo: "0609",
      CodigoVT: "51",
      CodigoZOHO: null,
      label: "PENIPE",
      value: "79",
    },
  },
  {
    label: "LATACUNGA",
    value: {
      CodigoProvincia: "6",
      CodigoCatalogo: "0501",
      CodigoVT: "36",
      CodigoZOHO: null,
      label: "LATACUNGA",
      value: "47",
    },
  },
  {
    label: "SALCEDO",
    value: {
      CodigoProvincia: "6",
      CodigoCatalogo: "0505",
      CodigoVT: "40",
      CodigoZOHO: null,
      label: "SALCEDO",
      value: "291",
    },
  },
  {
    label: "SAQUISILI",
    value: {
      CodigoProvincia: "6",
      CodigoCatalogo: "0506",
      CodigoVT: "41",
      CodigoZOHO: null,
      label: "SAQUISILI",
      value: "53",
    },
  },
  {
    label: "MACHALA",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0701",
      CodigoVT: "53",
      CodigoZOHO: null,
      label: "MACHALA",
      value: "162",
    },
  },
  {
    label: "ARENILLAS",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0702",
      CodigoVT: "54",
      CodigoZOHO: null,
      label: "ARENILLAS",
      value: "163",
    },
  },
  {
    label: "ATAHUALPA",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0703",
      CodigoVT: "55",
      CodigoZOHO: null,
      label: "ATAHUALPA",
      value: "164",
    },
  },
  {
    label: "BALSAS",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0704",
      CodigoVT: "56",
      CodigoZOHO: null,
      label: "BALSAS",
      value: "165",
    },
  },
  {
    label: "HUAQUILLAS",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0707",
      CodigoVT: "59",
      CodigoZOHO: null,
      label: "HUAQUILLAS",
      value: "168",
    },
  },
  {
    label: "MARCABELI",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0708",
      CodigoVT: "60",
      CodigoZOHO: null,
      label: "MARCABELI",
      value: "170",
    },
  },
  {
    label: "ZARUMA",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0713",
      CodigoVT: "65",
      CodigoZOHO: null,
      label: "ZARUMA",
      value: "175",
    },
  },
  {
    label: "ESMERALDAS",
    value: {
      CodigoProvincia: "8",
      CodigoCatalogo: "0801",
      CodigoVT: "67",
      CodigoZOHO: null,
      label: "ESMERALDAS",
      value: "182",
    },
  },
  {
    label: "ELOY ALFARO",
    value: {
      CodigoProvincia: "8",
      CodigoCatalogo: "0802",
      CodigoVT: "68",
      CodigoZOHO: null,
      label: "ELOY ALFARO",
      value: "120",
    },
  },
  {
    label: "ATACAMES",
    value: {
      CodigoProvincia: "8",
      CodigoCatalogo: "0806",
      CodigoVT: "72",
      CodigoZOHO: null,
      label: "ATACAMES",
      value: "119",
    },
  },
  {
    label: "RIOVERDE",
    value: {
      CodigoProvincia: "8",
      CodigoCatalogo: "0807",
      CodigoVT: "73",
      CodigoZOHO: null,
      label: "RIOVERDE",
      value: "295",
    },
  },
  {
    label: "ISABELA",
    value: {
      CodigoProvincia: "9",
      CodigoCatalogo: "2002",
      CodigoVT: "205",
      CodigoZOHO: null,
      label: "ISABELA",
      value: "181",
    },
  },
  {
    label: "GUAYAQUIL",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0901",
      CodigoVT: "75",
      CodigoZOHO: null,
      label: "GUAYAQUIL",
      value: "18",
    },
  },
  {
    label: "COLIMES",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0905",
      CodigoVT: "79",
      CodigoZOHO: null,
      label: "COLIMES",
      value: "11",
    },
  },
  {
    label: "DAULE",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0906",
      CodigoVT: "80",
      CodigoZOHO: null,
      label: "DAULE",
      value: "12",
    },
  },
  {
    label: "DURAN",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0907",
      CodigoVT: "81",
      CodigoZOHO: null,
      label: "DURAN",
      value: "13",
    },
  },
  {
    label: "EL TRIUNFO",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0909",
      CodigoVT: "83",
      CodigoZOHO: null,
      label: "EL TRIUNFO",
      value: "15",
    },
  },
  {
    label: "MILAGRO",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0910",
      CodigoVT: "84",
      CodigoZOHO: null,
      label: "MILAGRO",
      value: "23",
    },
  },
  {
    label: "NARANJITO",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0912",
      CodigoVT: "86",
      CodigoZOHO: null,
      label: "NARANJITO",
      value: "25",
    },
  },
  {
    label: "SAMBORONDON",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0916",
      CodigoVT: "89",
      CodigoZOHO: null,
      label: "SAMBORONDON",
      value: "30",
    },
  },
  {
    label: "SANTA LUCIA",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0918",
      CodigoVT: "90",
      CodigoZOHO: null,
      label: "SANTA LUCIA",
      value: "32",
    },
  },
  {
    label: "PLAYAS",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0921",
      CodigoVT: "93",
      CodigoZOHO: null,
      label: "PLAYAS",
      value: "301",
    },
  },
  {
    label: "SIMON BOLIVAR",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0922",
      CodigoVT: "94",
      CodigoZOHO: null,
      label: "SIMON BOLIVAR",
      value: "33",
    },
  },
  {
    label: "CORONEL MARCELINO MARIDUEÑA",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0923",
      CodigoVT: "95",
      CodigoZOHO: null,
      label: "CORONEL MARCELINO MARIDUEÑA",
      value: "303",
    },
  },
  {
    label: "NOBOL",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0925",
      CodigoVT: "97",
      CodigoZOHO: null,
      label: "NOBOL",
      value: "26",
    },
  },
  {
    label: "GENERAL ANTONIO ELIZALDE",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0927",
      CodigoVT: "98",
      CodigoZOHO: null,
      label: "GENERAL ANTONIO ELIZALDE",
      value: "304",
    },
  },
  {
    label: "ANTONIO ANTE",
    value: {
      CodigoProvincia: "11",
      CodigoCatalogo: "1002",
      CodigoVT: "101",
      CodigoZOHO: null,
      label: "ANTONIO ANTE",
      value: "44",
    },
  },
  {
    label: "OTAVALO",
    value: {
      CodigoProvincia: "11",
      CodigoCatalogo: "1004",
      CodigoVT: "103",
      CodigoZOHO: null,
      label: "OTAVALO",
      value: "42",
    },
  },
  {
    label: "SAN MIGUEL DE URCUQUI",
    value: {
      CodigoProvincia: "11",
      CodigoCatalogo: "1006",
      CodigoVT: "105",
      CodigoZOHO: null,
      label: "SAN MIGUEL DE URCUQUI",
      value: "305",
    },
  },
  {
    label: "LOJA",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1101",
      CodigoVT: "106",
      CodigoZOHO: null,
      label: "LOJA",
      value: "108",
    },
  },
  {
    label: "CATAMAYO",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1103",
      CodigoVT: "108",
      CodigoZOHO: null,
      label: "CATAMAYO",
      value: "103",
    },
  },
  {
    label: "ESPINDOLA",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1106",
      CodigoVT: "111",
      CodigoZOHO: null,
      label: "ESPINDOLA",
      value: "106",
    },
  },
  {
    label: "PALTAS",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1109",
      CodigoVT: "114",
      CodigoZOHO: null,
      label: "PALTAS",
      value: "111",
    },
  },
  {
    label: "SARAGURO",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1111",
      CodigoVT: "116",
      CodigoZOHO: null,
      label: "SARAGURO",
      value: "115",
    },
  },
  {
    label: "QUILANGA",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1115",
      CodigoVT: "120",
      CodigoZOHO: null,
      label: "QUILANGA",
      value: "114",
    },
  },
  {
    label: "OLMEDO",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1116",
      CodigoVT: "121",
      CodigoZOHO: null,
      label: "OLMEDO",
      value: "110",
    },
  },
  {
    label: "MONTALVO",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1203",
      CodigoVT: "124",
      CodigoZOHO: null,
      label: "MONTALVO",
      value: "151",
    },
  },
  {
    label: "QUEVEDO",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1205",
      CodigoVT: "126",
      CodigoZOHO: null,
      label: "QUEVEDO",
      value: "153",
    },
  },
  {
    label: "URDANETA",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1206",
      CodigoVT: "127",
      CodigoZOHO: null,
      label: "URDANETA",
      value: "154",
    },
  },
  {
    label: "BUENA FE",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1210",
      CodigoVT: "131",
      CodigoZOHO: null,
      label: "BUENA FE",
      value: "158",
    },
  },
  {
    label: "VALENCIA",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1211",
      CodigoVT: "132",
      CodigoZOHO: null,
      label: "VALENCIA",
      value: "159",
    },
  },
  {
    label: "QUINSALOMA",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1213",
      CodigoVT: "134",
      CodigoZOHO: null,
      label: "QUINSALOMA",
      value: "161",
    },
  },
  {
    label: "CHONE",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1303",
      CodigoVT: "137",
      CodigoZOHO: null,
      label: "CHONE",
      value: "130",
    },
  },
  {
    label: "JUNIN",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1307",
      CodigoVT: "141",
      CodigoZOHO: null,
      label: "JUNIN",
      value: "136",
    },
  },
  {
    label: "MANTA",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1308",
      CodigoVT: "142",
      CodigoZOHO: null,
      label: "MANTA",
      value: "137",
    },
  },
  {
    label: "ROCAFUERTE",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1312",
      CodigoVT: "146",
      CodigoZOHO: null,
      label: "ROCAFUERTE",
      value: "144",
    },
  },
  {
    label: "SANTA ANA",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1313",
      CodigoVT: "147",
      CodigoZOHO: null,
      label: "SANTA ANA",
      value: "146",
    },
  },
  {
    label: "SUCRE",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1314",
      CodigoVT: "148",
      CodigoZOHO: null,
      label: "SUCRE",
      value: "147",
    },
  },
  {
    label: "TOSAGUA",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1315",
      CodigoVT: "149",
      CodigoZOHO: null,
      label: "TOSAGUA",
      value: "148",
    },
  },
  {
    label: "JAMA",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1320",
      CodigoVT: "154",
      CodigoZOHO: null,
      label: "JAMA",
      value: "133",
    },
  },
  {
    label: "JARAMIJO",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1321",
      CodigoVT: "155",
      CodigoZOHO: null,
      label: "JARAMIJO",
      value: "134",
    },
  },
  {
    label: "SEVILLA DE ORO",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0113",
      CodigoVT: "13",
      CodigoZOHO: null,
      label: "SEVILLA DE ORO",
      value: "100",
    },
  },
  {
    label: "CAMILO PONCE ENRIQUEZ",
    value: {
      CodigoProvincia: "1",
      CodigoCatalogo: "0115",
      CodigoVT: "15",
      CodigoZOHO: null,
      label: "CAMILO PONCE ENRIQUEZ",
      value: "88",
    },
  },
  {
    label: "GUARANDA",
    value: {
      CodigoProvincia: "2",
      CodigoCatalogo: "0201",
      CodigoVT: "16",
      CodigoZOHO: null,
      label: "GUARANDA",
      value: "63",
    },
  },
  {
    label: "CHIMBO",
    value: {
      CodigoProvincia: "2",
      CodigoCatalogo: "0203",
      CodigoVT: "18",
      CodigoZOHO: null,
      label: "CHIMBO",
      value: "281",
    },
  },
  {
    label: "ECHEANDIA",
    value: {
      CodigoProvincia: "2",
      CodigoCatalogo: "0204",
      CodigoVT: "19",
      CodigoZOHO: null,
      label: "ECHEANDIA",
      value: "67",
    },
  },
  {
    label: "LAS NAVES",
    value: {
      CodigoProvincia: "2",
      CodigoCatalogo: "0207",
      CodigoVT: "22",
      CodigoZOHO: null,
      label: "LAS NAVES",
      value: "69",
    },
  },
  {
    label: "CAÑAR",
    value: {
      CodigoProvincia: "3",
      CodigoCatalogo: "0303",
      CodigoVT: "25",
      CodigoZOHO: null,
      label: "CAÑAR",
      value: "82",
    },
  },
  {
    label: "EL TAMBO",
    value: {
      CodigoProvincia: "3",
      CodigoCatalogo: "0305",
      CodigoVT: "27",
      CodigoZOHO: null,
      label: "EL TAMBO",
      value: "85",
    },
  },
  {
    label: "BOLIVAR",
    value: {
      CodigoProvincia: "4",
      CodigoCatalogo: "0402",
      CodigoVT: "31",
      CodigoZOHO: null,
      label: "BOLIVAR",
      value: "38",
    },
  },
  {
    label: "ESPEJO",
    value: {
      CodigoProvincia: "4",
      CodigoCatalogo: "0403",
      CodigoVT: "32",
      CodigoZOHO: null,
      label: "ESPEJO",
      value: "39",
    },
  },
  {
    label: "MIRA",
    value: {
      CodigoProvincia: "4",
      CodigoCatalogo: "0404",
      CodigoVT: "33",
      CodigoZOHO: null,
      label: "MIRA",
      value: "40",
    },
  },
  {
    label: "MONTUFAR",
    value: {
      CodigoProvincia: "4",
      CodigoCatalogo: "0405",
      CodigoVT: "34",
      CodigoZOHO: null,
      label: "MONTUFAR",
      value: "37",
    },
  },
  {
    label: "COLTA",
    value: {
      CodigoProvincia: "5",
      CodigoCatalogo: "0603",
      CodigoVT: "45",
      CodigoZOHO: null,
      label: "COLTA",
      value: "72",
    },
  },
  {
    label: "CHAMBO",
    value: {
      CodigoProvincia: "5",
      CodigoCatalogo: "0604",
      CodigoVT: "46",
      CodigoZOHO: null,
      label: "CHAMBO",
      value: "74",
    },
  },
  {
    label: "CHUNCHI",
    value: {
      CodigoProvincia: "5",
      CodigoCatalogo: "0605",
      CodigoVT: "47",
      CodigoZOHO: null,
      label: "CHUNCHI",
      value: "75",
    },
  },
  {
    label: "PALLATANGA",
    value: {
      CodigoProvincia: "5",
      CodigoCatalogo: "0608",
      CodigoVT: "50",
      CodigoZOHO: null,
      label: "PALLATANGA",
      value: "78",
    },
  },
  {
    label: "CUMANDA",
    value: {
      CodigoProvincia: "5",
      CodigoCatalogo: "0610",
      CodigoVT: "52",
      CodigoZOHO: null,
      label: "CUMANDA",
      value: "73",
    },
  },
  {
    label: "LA MANA",
    value: {
      CodigoProvincia: "6",
      CodigoCatalogo: "0502",
      CodigoVT: "37",
      CodigoZOHO: null,
      label: "LA MANA",
      value: "51",
    },
  },
  {
    label: "PANGUA",
    value: {
      CodigoProvincia: "6",
      CodigoCatalogo: "0503",
      CodigoVT: "38",
      CodigoZOHO: null,
      label: "PANGUA",
      value: "50",
    },
  },
  {
    label: "PUJILI",
    value: {
      CodigoProvincia: "6",
      CodigoCatalogo: "0504",
      CodigoVT: "39",
      CodigoZOHO: null,
      label: "PUJILI",
      value: "48",
    },
  },
  {
    label: "SIGCHOS",
    value: {
      CodigoProvincia: "6",
      CodigoCatalogo: "0507",
      CodigoVT: "42",
      CodigoZOHO: null,
      label: "SIGCHOS",
      value: "52",
    },
  },
  {
    label: "CHILLA",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0705",
      CodigoVT: "57",
      CodigoZOHO: null,
      label: "CHILLA",
      value: "166",
    },
  },
  {
    label: "EL GUABO",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0706",
      CodigoVT: "58",
      CodigoZOHO: null,
      label: "EL GUABO",
      value: "167",
    },
  },
  {
    label: "PASAJE",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0709",
      CodigoVT: "61",
      CodigoZOHO: null,
      label: "PASAJE",
      value: "171",
    },
  },
  {
    label: "PIÑAS",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0710",
      CodigoVT: "62",
      CodigoZOHO: null,
      label: "PIÑAS",
      value: "172",
    },
  },
  {
    label: "PORTOVELO",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0711",
      CodigoVT: "63",
      CodigoZOHO: null,
      label: "PORTOVELO",
      value: "173",
    },
  },
  {
    label: "SANTA ROSA",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0712",
      CodigoVT: "64",
      CodigoZOHO: null,
      label: "SANTA ROSA",
      value: "174",
    },
  },
  {
    label: "LAS LAJAS",
    value: {
      CodigoProvincia: "7",
      CodigoCatalogo: "0714",
      CodigoVT: "66",
      CodigoZOHO: null,
      label: "LAS LAJAS",
      value: "169",
    },
  },
  {
    label: "MUISNE",
    value: {
      CodigoProvincia: "8",
      CodigoCatalogo: "0803",
      CodigoVT: "69",
      CodigoZOHO: null,
      label: "MUISNE",
      value: "121",
    },
  },
  {
    label: "QUININDE",
    value: {
      CodigoProvincia: "8",
      CodigoCatalogo: "0804",
      CodigoVT: "70",
      CodigoZOHO: null,
      label: "QUININDE",
      value: "122",
    },
  },
  {
    label: "SAN LORENZO",
    value: {
      CodigoProvincia: "8",
      CodigoCatalogo: "0805",
      CodigoVT: "71",
      CodigoZOHO: null,
      label: "SAN LORENZO",
      value: "123",
    },
  },
  {
    label: "SANTA CRUZ",
    value: {
      CodigoProvincia: "9",
      CodigoCatalogo: "2003",
      CodigoVT: "206",
      CodigoZOHO: null,
      label: "SANTA CRUZ",
      value: "179",
    },
  },
  {
    label: "ALFREDO BAQUERIZO MORENO",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0902",
      CodigoVT: "76",
      CodigoZOHO: null,
      label: "ALFREDO BAQUERIZO MORENO",
      value: "9",
    },
  },
  {
    label: "BALAO",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0903",
      CodigoVT: "77",
      CodigoZOHO: null,
      label: "BALAO",
      value: "10",
    },
  },
  {
    label: "BALZAR",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0904",
      CodigoVT: "78",
      CodigoZOHO: null,
      label: "BALZAR",
      value: "296",
    },
  },
  {
    label: "EL EMPALME",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0908",
      CodigoVT: "82",
      CodigoZOHO: null,
      label: "EL EMPALME",
      value: "14",
    },
  },
  {
    label: "NARANJAL",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0911",
      CodigoVT: "85",
      CodigoZOHO: null,
      label: "NARANJAL",
      value: "24",
    },
  },
  {
    label: "PALESTINA",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0913",
      CodigoVT: "87",
      CodigoZOHO: null,
      label: "PALESTINA",
      value: "27",
    },
  },
  {
    label: "PEDRO CARBO",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0914",
      CodigoVT: "88",
      CodigoZOHO: null,
      label: "PEDRO CARBO",
      value: "28",
    },
  },
  {
    label: "SALITRE",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0919",
      CodigoVT: "91",
      CodigoZOHO: null,
      label: "SALITRE",
      value: "299",
    },
  },
  {
    label: "SAN JACINTO DE YAGUACHI",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0920",
      CodigoVT: "92",
      CodigoZOHO: null,
      label: "SAN JACINTO DE YAGUACHI",
      value: "34",
    },
  },
  {
    label: "LOMAS DE SARGENTILLO",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0924",
      CodigoVT: "96",
      CodigoZOHO: null,
      label: "LOMAS DE SARGENTILLO",
      value: "20",
    },
  },
  {
    label: "ISIDRO AYORA",
    value: {
      CodigoProvincia: "10",
      CodigoCatalogo: "0928",
      CodigoVT: "99",
      CodigoZOHO: null,
      label: "ISIDRO AYORA",
      value: "19",
    },
  },
  {
    label: "IBARRA",
    value: {
      CodigoProvincia: "11",
      CodigoCatalogo: "1001",
      CodigoVT: "100",
      CodigoZOHO: null,
      label: "IBARRA",
      value: "41",
    },
  },
  {
    label: "COTACACHI",
    value: {
      CodigoProvincia: "11",
      CodigoCatalogo: "1003",
      CodigoVT: "102",
      CodigoZOHO: null,
      label: "COTACACHI",
      value: "43",
    },
  },
  {
    label: "PIMAMPIRO",
    value: {
      CodigoProvincia: "11",
      CodigoCatalogo: "1005",
      CodigoVT: "104",
      CodigoZOHO: null,
      label: "PIMAMPIRO",
      value: "45",
    },
  },
  {
    label: "CALVAS",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1102",
      CodigoVT: "107",
      CodigoZOHO: null,
      label: "CALVAS",
      value: "183",
    },
  },
  {
    label: "CELICA",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1104",
      CodigoVT: "109",
      CodigoZOHO: null,
      label: "CELICA",
      value: "104",
    },
  },
  {
    label: "CHAGUARPAMBA",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1105",
      CodigoVT: "110",
      CodigoZOHO: null,
      label: "CHAGUARPAMBA",
      value: "306",
    },
  },
  {
    label: "GONZANAMA",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1107",
      CodigoVT: "112",
      CodigoZOHO: null,
      label: "GONZANAMA",
      value: "107",
    },
  },
  {
    label: "MACARA",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1108",
      CodigoVT: "113",
      CodigoZOHO: null,
      label: "MACARA",
      value: "109",
    },
  },
  {
    label: "PUYANGO",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1110",
      CodigoVT: "115",
      CodigoZOHO: null,
      label: "PUYANGO",
      value: "113",
    },
  },
  {
    label: "SOZORANGA",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1112",
      CodigoVT: "117",
      CodigoZOHO: null,
      label: "SOZORANGA",
      value: "116",
    },
  },
  {
    label: "ZAPOTILLO",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1113",
      CodigoVT: "118",
      CodigoZOHO: null,
      label: "ZAPOTILLO",
      value: "117",
    },
  },
  {
    label: "PINDAL",
    value: {
      CodigoProvincia: "12",
      CodigoCatalogo: "1114",
      CodigoVT: "119",
      CodigoZOHO: null,
      label: "PINDAL",
      value: "112",
    },
  },
  {
    label: "BABAHOYO",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1201",
      CodigoVT: "122",
      CodigoZOHO: null,
      label: "BABAHOYO",
      value: "149",
    },
  },
  {
    label: "BABA",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1202",
      CodigoVT: "123",
      CodigoZOHO: null,
      label: "BABA",
      value: "150",
    },
  },
  {
    label: "PUEBLOVIEJO",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1204",
      CodigoVT: "125",
      CodigoZOHO: null,
      label: "PUEBLOVIEJO",
      value: "310",
    },
  },
  {
    label: "VENTANAS",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1207",
      CodigoVT: "128",
      CodigoZOHO: null,
      label: "VENTANAS",
      value: "155",
    },
  },
  {
    label: "VINCES",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1208",
      CodigoVT: "129",
      CodigoZOHO: null,
      label: "VINCES",
      value: "156",
    },
  },
  {
    label: "PALENQUE",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1209",
      CodigoVT: "130",
      CodigoZOHO: null,
      label: "PALENQUE",
      value: "157",
    },
  },
  {
    label: "MOCACHE",
    value: {
      CodigoProvincia: "13",
      CodigoCatalogo: "1212",
      CodigoVT: "133",
      CodigoZOHO: null,
      label: "MOCACHE",
      value: "160",
    },
  },
  {
    label: "PORTOVIEJO",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1301",
      CodigoVT: "135",
      CodigoZOHO: null,
      label: "PORTOVIEJO",
      value: "312",
    },
  },
  {
    label: "BOLIVAR",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1302",
      CodigoVT: "136",
      CodigoZOHO: null,
      label: "BOLIVAR",
      value: "129",
    },
  },
  {
    label: "EL CARMEN",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1304",
      CodigoVT: "138",
      CodigoZOHO: null,
      label: "EL CARMEN",
      value: "131",
    },
  },
  {
    label: "FLAVIO ALFARO",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1305",
      CodigoVT: "139",
      CodigoZOHO: null,
      label: "FLAVIO ALFARO",
      value: "132",
    },
  },
  {
    label: "JIPIJAPA",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1306",
      CodigoVT: "140",
      CodigoZOHO: null,
      label: "JIPIJAPA",
      value: "135",
    },
  },
  {
    label: "MONTECRISTI",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1309",
      CodigoVT: "143",
      CodigoZOHO: null,
      label: "MONTECRISTI",
      value: "138",
    },
  },
  {
    label: "PAJAN",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1310",
      CodigoVT: "144",
      CodigoZOHO: null,
      label: "PAJAN",
      value: "140",
    },
  },
  {
    label: "PICHINCHA",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1311",
      CodigoVT: "145",
      CodigoZOHO: null,
      label: "PICHINCHA",
      value: "142",
    },
  },
  {
    label: "24 DE MAYO",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1316",
      CodigoVT: "150",
      CodigoZOHO: null,
      label: "24 DE MAYO",
      value: "128",
    },
  },
  {
    label: "PEDERNALES",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1317",
      CodigoVT: "151",
      CodigoZOHO: null,
      label: "PEDERNALES",
      value: "141",
    },
  },
  {
    label: "OLMEDO",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1318",
      CodigoVT: "152",
      CodigoZOHO: null,
      label: "OLMEDO",
      value: "139",
    },
  },
  {
    label: "PUERTO LOPEZ",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1319",
      CodigoVT: "153",
      CodigoZOHO: null,
      label: "PUERTO LOPEZ",
      value: "143",
    },
  },
  {
    label: "SAN VICENTE",
    value: {
      CodigoProvincia: "14",
      CodigoCatalogo: "1322",
      CodigoVT: "156",
      CodigoZOHO: null,
      label: "SAN VICENTE",
      value: "145",
    },
  },
  {
    label: "MORONA",
    value: {
      CodigoProvincia: "15",
      CodigoCatalogo: "1401",
      CodigoVT: "157",
      CodigoZOHO: null,
      label: "MORONA",
      value: "188",
    },
  },
  {
    label: "SAN CRISTOBAL",
    value: {
      CodigoProvincia: "9",
      CodigoCatalogo: "2001",
      CodigoVT: "204",
      CodigoZOHO: null,
      label: "SAN CRISTOBAL",
      value: "180",
    },
  },
];

export { listCantonFormsWeb };
